// packages/react-view/src/panel/components/PanelCanvas.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import InfiniteViewer from "react-infinite-viewer";
import { TransformComponent, TransformWrapper } from "react-zoom-pan-pinch";

import {
  clampViewportZoom,
  clampViewportZoomXY,
  type ViewportZoom,
} from "../viewportZoom";

export type PanelCanvasProps = {
  zoom: ViewportZoom;
  onZoomChange: (next: ViewportZoom) => void;
  contentSize?: { width: number; height: number } | null;
  onScrollChange?: (pos: { left: number; top: number }) => void;
  children: React.ReactNode;
  className?: string;
  canvasRef?: React.Ref<HTMLDivElement>;
  onCanvasMouseDownCapture?: React.MouseEventHandler<HTMLDivElement>;
  onCanvasClickCapture?: React.MouseEventHandler<HTMLDivElement>;
  onCanvasContextMenuCapture?: React.MouseEventHandler<HTMLDivElement>;
  onDropMaterial?: (payload: { materialId: string; x: number; y: number }) => void;
  /** 渲染在 InfiniteViewer 内、画布 scale 层之外（如 Moveable 控制框） */
  viewportOverlay?: React.ReactNode;
};

export const PanelCanvas = React.forwardRef<HTMLDivElement, PanelCanvasProps>(
  (
    {
      zoom,
      onZoomChange,
      contentSize = null,
      onScrollChange,
      children,
      className,
      canvasRef,
      onCanvasMouseDownCapture,
      onCanvasClickCapture,
      onCanvasContextMenuCapture,
      onDropMaterial,
      viewportOverlay,
    },
    scrollRef
  ) => {
  const viewportRef = useRef<HTMLDivElement | null>(null);
  const viewerRef = useRef<any>(null);
  const transformRef = useRef<any>(null);
  const canvasElRef = useRef<HTMLDivElement | null>(null);
  const syncingZoomRef = useRef(false);
  const didAutoCenterRef = useRef(false);
  const [isPanning, setIsPanning] = useState(false);
  const lastScrollRef = useRef({ left: 0, top: 0 });
  const zoomRef = useRef(zoom);
  const viewportSizeRef = useRef({ width: 0, height: 0 });
  const resizeZoomRafRef = useRef<number | null>(null);
  const resizeLayoutAnchorRef = useRef<{
    viewportWidth: number;
    viewportHeight: number;
    zoomX: number;
    zoomY: number;
    scrollLeft: number;
    scrollTop: number;
  } | null>(null);
  /** 上一次已应用的视口尺寸与分轴 zoom（每次 resize / 滚轮缩放后更新，保证开合蓝图可逆） */
  const layoutBaselineRef = useRef({
    viewportWidth: 0,
    viewportHeight: 0,
    zoomX: 1,
    zoomY: 1,
  });
  const [viewport, setViewport] = useState({ width: 0, height: 0 });
  /** 固定世界画布尺寸，不随 zoom / 当前视口变化，避免缩放与 DOM 尺寸竞态导致节点错位 */
  const [worldCanvasSize, setWorldCanvasSize] = useState<{
    width: number;
    height: number;
  } | null>(null);

  const commitScroll = useCallback(
    (left: number, top: number) => {
      const next = { left, top };
      lastScrollRef.current = next;
      onScrollChange?.(next);
    },
    [onScrollChange]
  );

  useEffect(() => {
    zoomRef.current = zoom;
  }, [zoom]);

  useEffect(() => {
    viewportSizeRef.current = viewport;
  }, [viewport]);

  useEffect(() => {
    if (contentSize) return;
    if (viewport.width < 8 || viewport.height < 8) return;
    setWorldCanvasSize((prev) => {
      if (prev) return prev;
      const size = { width: viewport.width, height: viewport.height };
      layoutBaselineRef.current = {
        viewportWidth: viewport.width,
        viewportHeight: viewport.height,
        zoomX: zoomRef.current.x,
        zoomY: zoomRef.current.y,
      };
      resizeLayoutAnchorRef.current = {
        viewportWidth: viewport.width,
        viewportHeight: viewport.height,
        zoomX: zoomRef.current.x,
        zoomY: zoomRef.current.y,
        scrollLeft: lastScrollRef.current.left,
        scrollTop: lastScrollRef.current.top,
      };
      return size;
    });
  }, [contentSize, viewport.height, viewport.width]);

  const panRef = useRef<{
    active: boolean;
    moved: boolean;
    startClientX: number;
    startClientY: number;
    startLeft: number;
    startTop: number;
  }>({
    active: false,
    moved: false,
    startClientX: 0,
    startClientY: 0,
    startLeft: 0,
    startTop: 0,
  });
  const panHandlersRef = useRef<{
    move: ((ev: MouseEvent) => void) | null;
    up: ((ev: MouseEvent) => void) | null;
  }>({ move: null, up: null });

  const clearWindowPanListeners = useCallback(() => {
    if (panHandlersRef.current.move) {
      window.removeEventListener("mousemove", panHandlersRef.current.move, true);
      panHandlersRef.current.move = null;
    }
    if (panHandlersRef.current.up) {
      window.removeEventListener("mouseup", panHandlersRef.current.up, true);
      panHandlersRef.current.up = null;
    }
  }, []);

  useEffect(() => clearWindowPanListeners, [clearWindowPanListeners]);

  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;

    const onWheelZoom = (e: WheelEvent) => {
      const api = transformRef.current;
      if (!api) return;
      const viewer = viewerRef.current as any;
      if (!viewer) return;
      const target = e.target as HTMLElement | null;
      if (
        target?.closest("input, textarea, select, [contenteditable='true']") ||
        target?.closest("[role='dialog']")
      ) {
        return;
      }
      e.preventDefault();
      const rect = el.getBoundingClientRect();
      const pointerX = e.clientX - rect.left;
      const pointerY = e.clientY - rect.top;
      const zx = zoomRef.current.x;
      const zy = zoomRef.current.y;
      const currentScrollLeft = Number(lastScrollRef.current.left ?? 0);
      const currentScrollTop = Number(lastScrollRef.current.top ?? 0);

      const direction = e.deltaY > 0 ? -1 : 1;
      const zoomStep = direction > 0 ? 1.08 : 0.92;
      const nextZoom = clampViewportZoomXY({
        x: zx * zoomStep,
        y: zy * zoomStep,
      });
      if (Math.abs(nextZoom.x - zx) < 0.0001 && Math.abs(nextZoom.y - zy) < 0.0001) {
        return;
      }

      const worldX = (pointerX + currentScrollLeft) / Math.max(0.0001, zx);
      const worldY = (pointerY + currentScrollTop) / Math.max(0.0001, zy);
      const nextScrollLeft = worldX * nextZoom.x - pointerX;
      const nextScrollTop = worldY * nextZoom.y - pointerY;

      syncingZoomRef.current = true;
      viewer.scrollTo(nextScrollLeft, nextScrollTop);
      commitScroll(nextScrollLeft, nextScrollTop);
      const { width: vw, height: vh } = viewportSizeRef.current;
      resizeLayoutAnchorRef.current = {
        viewportWidth: vw,
        viewportHeight: vh,
        zoomX: nextZoom.x,
        zoomY: nextZoom.y,
        scrollLeft: nextScrollLeft,
        scrollTop: nextScrollTop,
      };
      layoutBaselineRef.current = {
        viewportWidth: vw,
        viewportHeight: vh,
        zoomX: nextZoom.x,
        zoomY: nextZoom.y,
      };
      zoomRef.current = nextZoom;
      onZoomChange({
        x: Number(nextZoom.x.toFixed(4)),
        y: Number(nextZoom.y.toFixed(4)),
      });
      requestAnimationFrame(() => {
        syncingZoomRef.current = false;
      });
    };

    el.addEventListener("wheel", onWheelZoom, { passive: false, capture: true });
    return () => {
      el.removeEventListener("wheel", onWheelZoom, true);
    };
  }, [commitScroll, onZoomChange, viewport.width, viewport.height]);

  const applyViewportResizeZoom = useCallback(
    (w: number, h: number) => {
      if (w < 8 || h < 8) return;

      const viewer = viewerRef.current as {
        scrollTo?: (x: number, y: number) => void;
      } | null;
      if (!viewer) return;

      const baseline = layoutBaselineRef.current;
      if (baseline.viewportWidth < 8 || baseline.viewportHeight < 8) {
        layoutBaselineRef.current = {
          viewportWidth: w,
          viewportHeight: h,
          zoomX: zoomRef.current.x,
          zoomY: zoomRef.current.y,
        };
        resizeLayoutAnchorRef.current = {
          viewportWidth: w,
          viewportHeight: h,
          zoomX: zoomRef.current.x,
          zoomY: zoomRef.current.y,
          scrollLeft: lastScrollRef.current.left,
          scrollTop: lastScrollRef.current.top,
        };
        return;
      }

      if (
        Math.abs(w - baseline.viewportWidth) < 2 &&
        Math.abs(h - baseline.viewportHeight) < 2
      ) {
        return;
      }

      const factorX = w / baseline.viewportWidth;
      const factorY = h / baseline.viewportHeight;

      const anchor = resizeLayoutAnchorRef.current ?? {
        viewportWidth: w,
        viewportHeight: h,
        zoomX: zoomRef.current.x,
        zoomY: zoomRef.current.y,
        scrollLeft: lastScrollRef.current.left,
        scrollTop: lastScrollRef.current.top,
      };

      const nextZoomX = clampViewportZoom(baseline.zoomX * factorX);
      const nextZoomY = clampViewportZoom(baseline.zoomY * factorY);
      const worldX =
        (anchor.scrollLeft + anchor.viewportWidth / 2) /
        Math.max(0.0001, anchor.zoomX);
      const worldY =
        (anchor.scrollTop + anchor.viewportHeight / 2) /
        Math.max(0.0001, anchor.zoomY);
      const nextScrollLeft = worldX * nextZoomX - w / 2;
      const nextScrollTop = worldY * nextZoomY - h / 2;
      const nextZoom = { x: nextZoomX, y: nextZoomY };

      syncingZoomRef.current = true;
      viewer.scrollTo?.(nextScrollLeft, nextScrollTop);
      commitScroll(nextScrollLeft, nextScrollTop);
      resizeLayoutAnchorRef.current = {
        viewportWidth: w,
        viewportHeight: h,
        zoomX: nextZoomX,
        zoomY: nextZoomY,
        scrollLeft: nextScrollLeft,
        scrollTop: nextScrollTop,
      };
      layoutBaselineRef.current = {
        viewportWidth: w,
        viewportHeight: h,
        zoomX: nextZoomX,
        zoomY: nextZoomY,
      };
      zoomRef.current = nextZoom;
      onZoomChange({
        x: Number(nextZoomX.toFixed(4)),
        y: Number(nextZoomY.toFixed(4)),
      });
      requestAnimationFrame(() => {
        syncingZoomRef.current = false;
      });
    },
    [commitScroll, onZoomChange]
  );

  const syncViewportElement = useCallback(
    (el: HTMLDivElement | null) => {
      viewportRef.current = el;
      if (!scrollRef) return;
      if (typeof scrollRef === "function") scrollRef(el);
      else (scrollRef as React.MutableRefObject<HTMLDivElement | null>).current = el;
    },
    [scrollRef]
  );

  const syncCanvasElement = useCallback(
    (el: HTMLDivElement | null) => {
      canvasElRef.current = el;
      if (!canvasRef) return;
      if (typeof canvasRef === "function") canvasRef(el);
      else (canvasRef as React.MutableRefObject<HTMLDivElement | null>).current = el;
    },
    [canvasRef]
  );

  useEffect(() => {
    const container = viewerRef.current?.getContainer?.() as HTMLDivElement | undefined;
    syncViewportElement(container ?? null);
  }, [syncViewportElement]);

  useEffect(() => {
    if (didAutoCenterRef.current) return;
    const viewer = viewerRef.current as any;
    const viewportEl = viewportRef.current;
    if (!viewer || !viewportEl) return;

    const id = requestAnimationFrame(() => {
      const nodes = viewportEl.querySelectorAll<HTMLElement>(".rv-selectable");
      if (!nodes.length) return;

      let minX = Infinity;
      let minY = Infinity;
      let maxX = -Infinity;
      let maxY = -Infinity;

      nodes.forEach((node) => {
        const left = node.offsetLeft;
        const top = node.offsetTop;
        const width = node.offsetWidth;
        const height = node.offsetHeight;
        minX = Math.min(minX, left);
        minY = Math.min(minY, top);
        maxX = Math.max(maxX, left + width);
        maxY = Math.max(maxY, top + height);
      });

      if (!Number.isFinite(minX) || !Number.isFinite(minY)) return;
      const boundsWidth = Math.max(1, maxX - minX);
      const boundsHeight = Math.max(1, maxY - minY);

      const targetLeft = minX + boundsWidth / 2 - viewportEl.clientWidth / 2;
      const targetTop = minY + boundsHeight / 2 - viewportEl.clientHeight / 2;
      viewer.scrollTo(Math.round(targetLeft), Math.round(targetTop));
      didAutoCenterRef.current = true;
    });

    return () => cancelAnimationFrame(id);
  }, []);

  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;

    const update = () => {
      const width = Math.round(el.clientWidth);
      const height = Math.round(el.clientHeight);
      setViewport((prev) =>
        prev.width === width && prev.height === height ? prev : { width, height }
      );
    };
    update();

    if (typeof ResizeObserver !== "undefined") {
      const ro = new ResizeObserver(update);
      ro.observe(el);
      return () => ro.disconnect();
    }

    window.addEventListener("resize", update);
    return () => window.removeEventListener("resize", update);
  }, []);

  /** 操作区尺寸变化时同步缩放；基于上一次已应用的锚点，避免放大后滚动补偿错位 */
  useEffect(() => {
    if (contentSize) return;
    if (viewport.width < 8 || viewport.height < 8) return;

    if (resizeZoomRafRef.current != null) {
      cancelAnimationFrame(resizeZoomRafRef.current);
    }
    resizeZoomRafRef.current = requestAnimationFrame(() => {
      resizeZoomRafRef.current = null;
      applyViewportResizeZoom(viewport.width, viewport.height);
    });

    return () => {
      if (resizeZoomRafRef.current != null) {
        cancelAnimationFrame(resizeZoomRafRef.current);
      }
    };
  }, [
    applyViewportResizeZoom,
    contentSize,
    viewport.height,
    viewport.width,
  ]);

  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;
    const onContextMenu = (e: MouseEvent) => {
      // 只有发生了右键平移时，才拦截本次菜单；其余交给 shadcn ContextMenu
      if (panRef.current.moved) {
        e.preventDefault();
        e.stopPropagation();
        (e as any).stopImmediatePropagation?.();
        panRef.current.moved = false;
      }
    };
    const onMouseDown = (e: MouseEvent) => {
      // 右键 或 mac 上 ctrl+左键
      const isRightLike = e.button === 2 || (e.button === 0 && e.ctrlKey);
      if (!isRightLike) return;
      const viewer = viewerRef.current as any;
      if (!viewer) return;

      panRef.current.active = true;
      panRef.current.moved = false;
      panRef.current.startClientX = e.clientX;
      panRef.current.startClientY = e.clientY;
      panRef.current.startLeft = lastScrollRef.current.left;
      panRef.current.startTop = lastScrollRef.current.top;

      const move = (ev: MouseEvent) => {
        if (!panRef.current.active) return;
        const dx = ev.clientX - panRef.current.startClientX;
        const dy = ev.clientY - panRef.current.startClientY;
        const distance = Math.hypot(dx, dy);
        if (!panRef.current.moved && distance > 10) {
          panRef.current.moved = true;
          setIsPanning(true);
        }
        if (!panRef.current.moved) return;
        ev.preventDefault();
        viewer.scrollTo(panRef.current.startLeft - dx, panRef.current.startTop - dy);
      };

      const up = (ev: MouseEvent) => {
        if (!panRef.current.active) return;
        if (panRef.current.moved) {
          ev.preventDefault();
        }
        panRef.current.active = false;
        setIsPanning(false);
        clearWindowPanListeners();
      };

      panHandlersRef.current.move = move;
      panHandlersRef.current.up = up;
      window.addEventListener("mousemove", move, true);
      window.addEventListener("mouseup", up, true);
    };

    el.addEventListener("contextmenu", onContextMenu, true);
    el.addEventListener("mousedown", onMouseDown, true);
    return () => {
      el.removeEventListener("contextmenu", onContextMenu, true);
      el.removeEventListener("mousedown", onMouseDown, true);
    };
  }, [clearWindowPanListeners]);

  const resolvedContentSize = useMemo(() => {
    if (contentSize) return contentSize;
    if (worldCanvasSize) return worldCanvasSize;
    return {
      width: Math.max(0, viewport.width),
      height: Math.max(0, viewport.height),
    };
  }, [contentSize, viewport.height, viewport.width, worldCanvasSize]);

  const style = useMemo<React.CSSProperties>(
    () => ({
      width: resolvedContentSize.width,
      height: resolvedContentSize.height,
      minWidth: "100%",
      minHeight: "100%",
      position: "relative",
      transform: `scale(${zoom.x}, ${zoom.y})`,
      transformOrigin: "0 0",
    }),
    [resolvedContentSize.height, resolvedContentSize.width, zoom.x, zoom.y]
  );

  const hasMaterialPayload = useCallback((types: ArrayLike<string> | null | undefined) => {
    if (!types) return false;
    return Array.from(types).includes("application/x-arron-material");
  }, []);

  const commitDropFromPoint = useCallback(
    (clientX: number, clientY: number, dataTransfer: DataTransfer | null) => {
      const raw = dataTransfer?.getData("application/x-arron-material");
      if (!raw) return;
      try {
        const material = JSON.parse(raw) as { id?: string };
        if (!material?.id) return;
        const viewportEl = viewportRef.current;
        if (!viewportEl) return;
        const viewportRect = viewportEl.getBoundingClientRect();
        const localX = clientX - viewportRect.left;
        const localY = clientY - viewportRect.top;
        const isInsideViewport =
          localX >= 0 &&
          localY >= 0 &&
          localX <= viewportRect.width &&
          localY <= viewportRect.height;
        if (!isInsideViewport) return;
        const canvasEl = canvasElRef.current;
        if (!canvasEl) return;
        const canvasRect = canvasEl.getBoundingClientRect();
        const x = (clientX - canvasRect.left) / Math.max(0.0001, zoomRef.current.x);
        const y = (clientY - canvasRect.top) / Math.max(0.0001, zoomRef.current.y);
        onDropMaterial?.({ materialId: material.id, x, y });
      } catch {
        // ignore invalid payload
      }
    },
    [onDropMaterial]
  );

  useEffect(() => {
    const el = viewportRef.current;
    if (!el) return;

    const onDragOver = (e: DragEvent) => {
      if (!hasMaterialPayload(e.dataTransfer?.types)) return;
      e.preventDefault();
      if (e.dataTransfer) e.dataTransfer.dropEffect = "copy";
    };

    const onDrop = (e: DragEvent) => {
      if (!hasMaterialPayload(e.dataTransfer?.types)) return;
      e.preventDefault();
      commitDropFromPoint(e.clientX, e.clientY, e.dataTransfer ?? null);
    };

    el.addEventListener("dragover", onDragOver, true);
    el.addEventListener("drop", onDrop, true);
    return () => {
      el.removeEventListener("dragover", onDragOver, true);
      el.removeEventListener("drop", onDrop, true);
    };
  }, [commitDropFromPoint, hasMaterialPayload]);

  return (
    <InfiniteViewer
      ref={viewerRef}
      className={[
        // 禁用原生滚动条外观（InfiniteViewer 自己的滚动条也会被下面的 props 关闭）
        "relative h-full w-full overflow-hidden bg-background [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden",
        isPanning ? "cursor-grabbing select-none" : "",
        className ?? "",
      ].join(" ")}
      style={{
        backgroundImage:
          "linear-gradient(to right, hsl(var(--border) / 0.45) 1px, transparent 1px), linear-gradient(to bottom, hsl(var(--border) / 0.45) 1px, transparent 1px)",
        backgroundSize: "20px 20px",
      }}
      margin={0}
      threshold={0}
      // 只允许右键平移：禁用 InfiniteViewer 的默认鼠标拖拽（通常是左键）
      useMouseDrag={false}
      // 不显示滚动条 & 禁用滚轮滚动（类型定义未暴露这些 props，按 any 透传）
      {...({
        displayVerticalScroll: false,
        displayHorizontalScroll: false,
        useWheelScroll: false,
      } as any)}
      preventWheelClick
      onScroll={(e: any) => {
        const next = { left: e.scrollLeft ?? 0, top: e.scrollTop ?? 0 };
        lastScrollRef.current = next;
        onScrollChange?.(next);
      }}
    >
      <TransformWrapper
        ref={transformRef}
        initialScale={1}
        minScale={1}
        maxScale={1}
        centerOnInit={false}
        limitToBounds={false}
        panning={{ disabled: true }}
        doubleClick={{ disabled: true }}
        pinch={{ disabled: true }}
        wheel={{ step: 0.008, disabled: true, wheelDisabled: true }}
        centerZoomedOut={false}
      >
        <TransformComponent
          // 始终占满操作容器，但不在这一层裁切放大后的内容
          wrapperStyle={{ width: "100%", height: "100%", overflow: "visible" }}
          contentStyle={{ width: "100%", height: "100%", overflow: "visible" }}
        >
          <div
            ref={syncCanvasElement}
            data-panel-canvas
            style={style}
            className=""
            onMouseDownCapture={onCanvasMouseDownCapture}
            onClickCapture={onCanvasClickCapture}
            onContextMenuCapture={onCanvasContextMenuCapture}
          >
            {children}
          </div>
        </TransformComponent>
      </TransformWrapper>
      {viewportOverlay ? (
        <div className="rv-viewport-overlay pointer-events-none absolute inset-0 z-[70] overflow-visible [&_.moveable-control-box]:pointer-events-auto">
          {viewportOverlay}
        </div>
      ) : null}
    </InfiniteViewer>
  );
}
);

PanelCanvas.displayName = "PanelCanvas";

// packages/vue-view/src/panel/components/PanelCanvas.vue
<script setup lang="ts">
import {
  computed,
  nextTick,
  onMounted,
  onUnmounted,
  ref,
  shallowRef,
  useTemplateRef,
  watch,
} from "vue";
import InfiniteViewer from "infinite-viewer";
import {
  clampViewportZoom,
  clampViewportZoomXY,
  uniformViewportZoom,
  type ViewportZoom,
} from "../viewportZoom";

const props = withDefaults(
  defineProps<{
    zoom: ViewportZoom;
    contentSize?: { width: number; height: number } | null;
    class?: string;
    canvasRef?: (el: HTMLDivElement | null) => void;
    scrollRef?: (el: HTMLDivElement | null) => void;
    viewportSyncRef?: { current: (() => void) | null };
    onDropMaterial?: (payload: { materialId: string; x: number; y: number }) => void;
    onCanvasMouseDownCapture?: (e: MouseEvent) => void;
    onCanvasClickCapture?: (e: MouseEvent) => void;
    onCanvasContextMenuCapture?: (e: MouseEvent) => void;
  }>(),
  { contentSize: null }
);

const emit = defineEmits<{
  zoomChange: [next: ViewportZoom];
  scrollChange: [pos: { left: number; top: number }];
}>();

const viewerHostRef = useTemplateRef<HTMLDivElement>("viewerHost");
const viewportRef = useTemplateRef<HTMLDivElement>("viewport");
const canvasElRef = useTemplateRef<HTMLDivElement>("canvasEl");

const viewerRef = shallowRef<InfiniteViewer | null>(null);
const syncingZoomRef = ref(false);
const didAutoCenterRef = ref(false);
const isPanning = ref(false);
const lastScrollRef = ref({ left: 0, top: 0 });
const zoomRef = ref({ ...props.zoom });
const viewportSizeRef = ref({ width: 0, height: 0 });
const viewport = ref({ width: 0, height: 0 });
const worldCanvasSize = ref<{ width: number; height: number } | null>(null);

const resizeZoomRafRef = ref<number | null>(null);
const resizeLayoutAnchorRef = ref<{
  viewportWidth: number;
  viewportHeight: number;
  zoomX: number;
  zoomY: number;
  scrollLeft: number;
  scrollTop: number;
} | null>(null);
const layoutBaselineRef = ref({
  viewportWidth: 0,
  viewportHeight: 0,
  zoomX: 1,
  zoomY: 1,
});

const panRef = ref({
  active: false,
  moved: false,
  startClientX: 0,
  startClientY: 0,
  startLeft: 0,
  startTop: 0,
});
const panHandlersRef = ref<{
  move: ((ev: MouseEvent) => void) | null;
  up: ((ev: MouseEvent) => void) | null;
}>({ move: null, up: null });

function applyCanvasTransform(scale: number) {
  const el = canvasElRef.value;
  if (!el) return;
  el.style.transform = `scale(${scale})`;
  el.style.transformOrigin = "0 0";
  el.dataset.canvasScale = String(scale);
}

function notifyViewportSync() {
  props.viewportSyncRef?.current?.();
}

function syncViewportElement(el: HTMLDivElement | null) {
  props.scrollRef?.(el);
}

function syncCanvasElement(el: HTMLDivElement | null) {
  if (el) {
    applyCanvasTransform(uniformViewportZoom(zoomRef.value));
  }
  props.canvasRef?.(el);
}

function clearWindowPanListeners() {
  if (panHandlersRef.value.move) {
    window.removeEventListener("mousemove", panHandlersRef.value.move, true);
    panHandlersRef.value.move = null;
  }
  if (panHandlersRef.value.up) {
    window.removeEventListener("mouseup", panHandlersRef.value.up, true);
    panHandlersRef.value.up = null;
  }
}

const resolvedContentSize = computed(() => {
  if (props.contentSize) return props.contentSize;
  if (worldCanvasSize.value) return worldCanvasSize.value;
  return {
    width: Math.max(0, viewport.value.width),
    height: Math.max(0, viewport.value.height),
  };
});

const canvasScale = computed(() => uniformViewportZoom(props.zoom));

const worldStyle = computed(() => ({
  width: `${resolvedContentSize.value.width}px`,
  height: `${resolvedContentSize.value.height}px`,
  position: "relative" as const,
}));

const canvasStyle = computed(() => ({
  width: `${resolvedContentSize.value.width}px`,
  height: `${resolvedContentSize.value.height}px`,
  minWidth: "100%",
  minHeight: "100%",
  position: "relative" as const,
  transformOrigin: "0 0",
}));

function applyViewportResizeZoom(w: number, h: number) {
  if (w < 8 || h < 8) return;
  if (syncingZoomRef.value) return;

  const viewer = viewerRef.value;
  if (!viewer) return;

  const baseline = layoutBaselineRef.value;
  if (baseline.viewportWidth < 8 || baseline.viewportHeight < 8) {
    layoutBaselineRef.value = {
      viewportWidth: w,
      viewportHeight: h,
      zoomX: zoomRef.value.x,
      zoomY: zoomRef.value.y,
    };
    resizeLayoutAnchorRef.value = {
      viewportWidth: w,
      viewportHeight: h,
      zoomX: zoomRef.value.x,
      zoomY: zoomRef.value.y,
      scrollLeft: lastScrollRef.value.left,
      scrollTop: lastScrollRef.value.top,
    };
    return;
  }

  if (
    Math.abs(w - baseline.viewportWidth) < 2 &&
    Math.abs(h - baseline.viewportHeight) < 2
  ) {
    return;
  }

  const factorX = w / baseline.viewportWidth;
  const factorY = h / baseline.viewportHeight;
  const factor = Math.sqrt(factorX * factorY);

  const anchor = resizeLayoutAnchorRef.value ?? {
    viewportWidth: w,
    viewportHeight: h,
    zoomX: zoomRef.value.x,
    zoomY: zoomRef.value.y,
    scrollLeft: lastScrollRef.value.left,
    scrollTop: lastScrollRef.value.top,
  };

  const nextZoomValue = clampViewportZoom(baseline.zoomX * factor);
  const worldX =
    (anchor.scrollLeft + anchor.viewportWidth / 2) / Math.max(0.0001, anchor.zoomX);
  const worldY =
    (anchor.scrollTop + anchor.viewportHeight / 2) / Math.max(0.0001, anchor.zoomY);
  const nextScrollLeft = worldX * nextZoomValue - w / 2;
  const nextScrollTop = worldY * nextZoomValue - h / 2;
  const nextZoom = { x: nextZoomValue, y: nextZoomValue };

  syncingZoomRef.value = true;
  zoomRef.value = nextZoom;
  applyCanvasTransform(nextZoomValue);
  viewer.scrollTo(nextScrollLeft, nextScrollTop);
  resizeLayoutAnchorRef.value = {
    viewportWidth: w,
    viewportHeight: h,
    zoomX: nextZoomValue,
    zoomY: nextZoomValue,
    scrollLeft: nextScrollLeft,
    scrollTop: nextScrollTop,
  };
  layoutBaselineRef.value = {
    viewportWidth: w,
    viewportHeight: h,
    zoomX: nextZoomValue,
    zoomY: nextZoomValue,
  };
  emit("zoomChange", {
    x: Number(nextZoomValue.toFixed(4)),
    y: Number(nextZoomValue.toFixed(4)),
  });
}

function hasMaterialPayload(types: ArrayLike<string> | null | undefined) {
  if (!types) return false;
  return Array.from(types).includes("application/x-arronqzy-material");
}

function commitDropFromPoint(
  clientX: number,
  clientY: number,
  dataTransfer: DataTransfer | null
) {
  const raw = dataTransfer?.getData("application/x-arronqzy-material");
  if (!raw) return;
  try {
    const material = JSON.parse(raw) as { id?: string };
    if (!material?.id) return;
    const viewportEl = viewerRef.value?.getContainer?.() as HTMLDivElement | undefined;
    if (!viewportEl) return;
    const viewportRect = viewportEl.getBoundingClientRect();
    const localX = clientX - viewportRect.left;
    const localY = clientY - viewportRect.top;
    const isInsideViewport =
      localX >= 0 &&
      localY >= 0 &&
      localX <= viewportRect.width &&
      localY <= viewportRect.height;
    if (!isInsideViewport) return;
    const canvasEl = canvasElRef.value;
    if (!canvasEl) return;
    const canvasRect = canvasEl.getBoundingClientRect();
    const x = (clientX - canvasRect.left) / Math.max(0.0001, zoomRef.value.x);
    const y = (clientY - canvasRect.top) / Math.max(0.0001, zoomRef.value.y);
    props.onDropMaterial?.({ materialId: material.id, x, y });
  } catch {
    // ignore invalid payload
  }
}

function setupWheelZoom(el: HTMLDivElement) {
  const onWheelZoom = (e: WheelEvent) => {
    const viewer = viewerRef.value;
    if (!viewer) return;
    const target = e.target as HTMLElement | null;
    if (
      target?.closest("input, textarea, select, [contenteditable='true']") ||
      target?.closest("[role='dialog']")
    ) {
      return;
    }
    e.preventDefault();
    const rect = el.getBoundingClientRect();
    const pointerX = e.clientX - rect.left;
    const pointerY = e.clientY - rect.top;
    const zx = zoomRef.value.x;
    const zy = zoomRef.value.y;
    const currentScrollLeft = Number(lastScrollRef.value.left ?? 0);
    const currentScrollTop = Number(lastScrollRef.value.top ?? 0);

    const direction = e.deltaY > 0 ? -1 : 1;
    const zoomStep = direction > 0 ? 1.08 : 0.92;
    const nextZoom = clampViewportZoomXY({
      x: zx * zoomStep,
      y: zy * zoomStep,
    });
    if (Math.abs(nextZoom.x - zx) < 0.0001 && Math.abs(nextZoom.y - zy) < 0.0001) {
      return;
    }

    const worldX = (pointerX + currentScrollLeft) / Math.max(0.0001, zx);
    const worldY = (pointerY + currentScrollTop) / Math.max(0.0001, zy);
    const nextScrollLeft = worldX * nextZoom.x - pointerX;
    const nextScrollTop = worldY * nextZoom.y - pointerY;
    const nextScale = uniformViewportZoom(nextZoom);

    syncingZoomRef.value = true;
    zoomRef.value = nextZoom;
    applyCanvasTransform(nextScale);
    viewer.scrollTo(nextScrollLeft, nextScrollTop);
    const { width: vw, height: vh } = viewportSizeRef.value;
    resizeLayoutAnchorRef.value = {
      viewportWidth: vw,
      viewportHeight: vh,
      zoomX: nextZoom.x,
      zoomY: nextZoom.y,
      scrollLeft: nextScrollLeft,
      scrollTop: nextScrollTop,
    };
    layoutBaselineRef.value = {
      viewportWidth: vw,
      viewportHeight: vh,
      zoomX: nextZoom.x,
      zoomY: nextZoom.y,
    };
    emit("zoomChange", {
      x: Number(nextZoom.x.toFixed(4)),
      y: Number(nextZoom.y.toFixed(4)),
    });
  };

  el.addEventListener("wheel", onWheelZoom, { passive: false, capture: true });
  return () => el.removeEventListener("wheel", onWheelZoom, true);
}

function setupPanHandlers(el: HTMLDivElement) {
  const onContextMenu = (e: MouseEvent) => {
    if (panRef.value.moved) {
      e.preventDefault();
      e.stopPropagation();
      (e as Event & { stopImmediatePropagation?: () => void }).stopImmediatePropagation?.();
      panRef.value.moved = false;
    }
  };

  const onMouseDown = (e: MouseEvent) => {
    const isRightLike = e.button === 2 || (e.button === 0 && e.ctrlKey);
    if (!isRightLike) return;
    const viewer = viewerRef.value;
    if (!viewer) return;

    panRef.value.active = true;
    panRef.value.moved = false;
    panRef.value.startClientX = e.clientX;
    panRef.value.startClientY = e.clientY;
    panRef.value.startLeft = lastScrollRef.value.left;
    panRef.value.startTop = lastScrollRef.value.top;

    const move = (ev: MouseEvent) => {
      if (!panRef.value.active) return;
      const dx = ev.clientX - panRef.value.startClientX;
      const dy = ev.clientY - panRef.value.startClientY;
      const distance = Math.hypot(dx, dy);
      if (!panRef.value.moved && distance > 10) {
        panRef.value.moved = true;
        isPanning.value = true;
      }
      if (!panRef.value.moved) return;
      ev.preventDefault();
      const nextLeft = panRef.value.startLeft - dx;
      const nextTop = panRef.value.startTop - dy;
      viewer.scrollTo(nextLeft, nextTop);
      lastScrollRef.value = { left: nextLeft, top: nextTop };
      emit("scrollChange", { left: nextLeft, top: nextTop });
      notifyViewportSync();
    };

    const up = (ev: MouseEvent) => {
      if (!panRef.value.active) return;
      if (panRef.value.moved) {
        ev.preventDefault();
      }
      panRef.value.active = false;
      isPanning.value = false;
      clearWindowPanListeners();
    };

    panHandlersRef.value.move = move;
    panHandlersRef.value.up = up;
    window.addEventListener("mousemove", move, true);
    window.addEventListener("mouseup", up, true);
  };

  el.addEventListener("contextmenu", onContextMenu, true);
  el.addEventListener("mousedown", onMouseDown, true);
  return () => {
    el.removeEventListener("contextmenu", onContextMenu, true);
    el.removeEventListener("mousedown", onMouseDown, true);
  };
}

function setupDropHandlers(el: HTMLDivElement) {
  const onDragOver = (e: DragEvent) => {
    if (!hasMaterialPayload(e.dataTransfer?.types)) return;
    e.preventDefault();
    if (e.dataTransfer) e.dataTransfer.dropEffect = "copy";
  };

  const onDrop = (e: DragEvent) => {
    if (!hasMaterialPayload(e.dataTransfer?.types)) return;
    e.preventDefault();
    commitDropFromPoint(e.clientX, e.clientY, e.dataTransfer ?? null);
  };

  el.addEventListener("dragover", onDragOver, true);
  el.addEventListener("drop", onDrop, true);
  return () => {
    el.removeEventListener("dragover", onDragOver, true);
    el.removeEventListener("drop", onDrop, true);
  };
}

let cleanupWheel: (() => void) | null = null;
let cleanupPan: (() => void) | null = null;
let cleanupDrop: (() => void) | null = null;
let resizeObserver: ResizeObserver | null = null;

watch(
  () => props.zoom,
  (zoom) => {
    zoomRef.value = zoom;
  },
  { immediate: true, deep: true }
);

watch(viewport, (v) => {
  viewportSizeRef.value = v;
});

watch(
  () => [props.contentSize, viewport.value.width, viewport.value.height] as const,
  () => {
    if (props.contentSize) return;
    if (viewport.value.width < 8 || viewport.value.height < 8) return;
    if (worldCanvasSize.value) return;
    const size = { width: viewport.value.width, height: viewport.value.height };
    layoutBaselineRef.value = {
      viewportWidth: viewport.value.width,
      viewportHeight: viewport.value.height,
      zoomX: zoomRef.value.x,
      zoomY: zoomRef.value.y,
    };
    resizeLayoutAnchorRef.value = {
      viewportWidth: viewport.value.width,
      viewportHeight: viewport.value.height,
      zoomX: zoomRef.value.x,
      zoomY: zoomRef.value.y,
      scrollLeft: lastScrollRef.value.left,
      scrollTop: lastScrollRef.value.top,
    };
    worldCanvasSize.value = size;
  }
);

watch(canvasScale, () => {
  const scale = syncingZoomRef.value
    ? uniformViewportZoom(zoomRef.value)
    : uniformViewportZoom(props.zoom);
  applyCanvasTransform(scale);
});

watch(
  () => [props.zoom.x, props.zoom.y] as const,
  () => {
    if (
      Math.abs(props.zoom.x - zoomRef.value.x) < 0.0001 &&
      Math.abs(props.zoom.y - zoomRef.value.y) < 0.0001
    ) {
      syncingZoomRef.value = false;
    }
  }
);

watch(
  () => [viewport.value.width, viewport.value.height, props.contentSize] as const,
  () => {
    if (props.contentSize) return;
    if (viewport.value.width < 8 || viewport.value.height < 8) return;

    if (resizeZoomRafRef.value != null) {
      cancelAnimationFrame(resizeZoomRafRef.value);
    }
    resizeZoomRafRef.value = requestAnimationFrame(() => {
      resizeZoomRafRef.value = null;
      applyViewportResizeZoom(viewport.value.width, viewport.value.height);
    });
  }
);

watch(canvasElRef, (el) => syncCanvasElement(el), { immediate: true });

onMounted(async () => {
  const host = viewerHostRef.value;
  const viewportEl = viewportRef.value;
  if (!host || !viewportEl) return;

  const viewer = new InfiniteViewer(host, viewportEl, {
    margin: 0,
    threshold: 0,
    useMouseDrag: false,
    displayVerticalScroll: false,
    displayHorizontalScroll: false,
    useWheelScroll: false,
    preventWheelClick: true,
  });
  viewerRef.value = viewer;

  viewer.on("scroll", () => {
    const next = {
      left: viewer.getScrollLeft(),
      top: viewer.getScrollTop(),
    };
    lastScrollRef.value = next;
    emit("scrollChange", next);
    if (!syncingZoomRef.value) {
      notifyViewportSync();
    }
  });

  await nextTick();
  const container = viewer.getContainer() as HTMLDivElement | null;
  syncViewportElement(container);

  const updateViewportSize = () => {
    if (!container) return;
    const width = Math.round(container.clientWidth);
    const height = Math.round(container.clientHeight);
    if (viewport.value.width !== width || viewport.value.height !== height) {
      viewport.value = { width, height };
    }
  };
  updateViewportSize();

  if (container) {
    if (typeof ResizeObserver !== "undefined") {
      resizeObserver = new ResizeObserver(updateViewportSize);
      resizeObserver.observe(container);
    } else {
      window.addEventListener("resize", updateViewportSize);
    }

    cleanupWheel = setupWheelZoom(container);
    cleanupPan = setupPanHandlers(container);
    cleanupDrop = setupDropHandlers(container);
  }

  requestAnimationFrame(() => {
    if (!container || didAutoCenterRef.value) return;
    const nodes = container.querySelectorAll<HTMLElement>(".rv-selectable");
    if (!nodes.length) return;

    let minX = Infinity;
    let minY = Infinity;
    let maxX = -Infinity;
    let maxY = -Infinity;

    nodes.forEach((node) => {
      const left = node.offsetLeft;
      const top = node.offsetTop;
      const width = node.offsetWidth;
      const height = node.offsetHeight;
      minX = Math.min(minX, left);
      minY = Math.min(minY, top);
      maxX = Math.max(maxX, left + width);
      maxY = Math.max(maxY, top + height);
    });

    if (!Number.isFinite(minX) || !Number.isFinite(minY)) return;
    const boundsWidth = Math.max(1, maxX - minX);
    const boundsHeight = Math.max(1, maxY - minY);

    const targetLeft = minX + boundsWidth / 2 - container.clientWidth / 2;
    const targetTop = minY + boundsHeight / 2 - container.clientHeight / 2;
    viewer.scrollTo(Math.round(targetLeft), Math.round(targetTop));
    didAutoCenterRef.value = true;
  });
});

onUnmounted(() => {
  clearWindowPanListeners();
  cleanupWheel?.();
  cleanupPan?.();
  cleanupDrop?.();
  resizeObserver?.disconnect();
  if (resizeZoomRafRef.value != null) {
    cancelAnimationFrame(resizeZoomRafRef.value);
  }
  viewerRef.value?.destroy();
  viewerRef.value = null;
  syncViewportElement(null);
  syncCanvasElement(null);
});
</script>

<template>
  <div
    ref="viewerHost"
    :class="[
      'relative h-full w-full overflow-hidden bg-background [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden',
      isPanning ? 'cursor-grabbing select-none' : '',
      props.class ?? '',
    ]"
    :style="{
      backgroundImage:
        'linear-gradient(to right, hsl(var(--border) / 0.45) 1px, transparent 1px), linear-gradient(to bottom, hsl(var(--border) / 0.45) 1px, transparent 1px)',
      backgroundSize: '20px 20px',
    }"
  >
    <div ref="viewport">
      <div :style="worldStyle">
        <div
          ref="canvasEl"
          data-panel-canvas
          :style="canvasStyle"
          class="h-full w-full"
          @mousedown.capture="props.onCanvasMouseDownCapture"
          @click.capture="props.onCanvasClickCapture"
          @contextmenu.capture="props.onCanvasContextMenuCapture"
        >
          <slot />
        </div>
        <div
          v-if="$slots['viewport-overlay']"
          class="rv-viewport-overlay pointer-events-none absolute inset-0 z-[70] overflow-visible [&_.moveable-control-box]:pointer-events-auto [&_.moveable-group]:pointer-events-auto [&_.moveable-area]:pointer-events-auto"
        >
          <slot name="viewport-overlay" />
        </div>
      </div>
    </div>
  </div>
</template>
