// packages/react-view/src/panel/components/config/PanelConfigStyleSections.tsx
import React, { useCallback, useState } from "react";
import { useI18n } from "@arronqzy/i18n/react";
import {
  Input,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@arronqzy/ui";
import type { PanelElement, PanelElementStyle } from "../../types";
import { readFileAsDataUrl, runBusyTask } from "../../utils/async-work";
import { patchBackgroundImageFromInput } from "../../utils/background-image-style";
import { getPanelMessages } from "../../constants/messages";
import { type ConfigSectionHelpers, type UpdateElement } from "./helpers";

export function PanelConfigStyleSections({
  element,
  helpers,
  updateElement,
}: {
  element: PanelElement;
  helpers: ConfigSectionHelpers;
  updateElement: UpdateElement;
}) {
  const { t } = useI18n();
  const messages = React.useMemo(() => getPanelMessages(t), [t]);
  const { renderSection, renderFieldGroup, renderColorField } = helpers;
  const selectedElement = element;
  const [uploadStatus, setUploadStatus] = useState("");

  const updateSelectedStyle = useCallback(
    (patch: Partial<PanelElementStyle>) => {
      updateElement(selectedElement.id, {
        style: { ...(selectedElement.style ?? {}), ...patch },
      });
    },
    [selectedElement, updateElement]
  );

  const handleUploadBackgroundImage = useCallback(
    async (file: File) => {
      try {
        await runBusyTask(t("common.uploadingFile"), async () => {
          const base64 = await readFileAsDataUrl(file, messages.readImageFailed, "image");
          updateSelectedStyle({
            backgroundImage: `url("${base64}")`,
          });
          setUploadStatus(t("panel.config.uploadWrittenBase64"));
          try {
            const form = new FormData();
            form.append("file", file);
            const resp = await fetch("/api/upload", { method: "POST", body: form });
            if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
            const data = (await resp.json()) as { url?: string };
            if (data.url) {
              updateSelectedStyle({ backgroundImageRemoteUrl: data.url });
              setUploadStatus(t("panel.config.uploadServerAndBase64"));
            }
          } catch {
            setUploadStatus(t("panel.config.uploadServerFailedKeepBase64"));
          }
        });
      } catch (error) {
        setUploadStatus(
          error instanceof Error ? error.message : messages.readImageFailed
        );
      }
    },
    [messages.readImageFailed, t, updateSelectedStyle]
  );

  return (
    <>
          {renderSection(
            "styleBackground",
            t("panel.config.sectionStyleBackground"),
            <>
              {renderFieldGroup(
                t("panel.config.groupBgFill"),
                <>
                  {renderColorField(
                    t("panel.config.backgroundColor"),
                    selectedElement.style?.backgroundColor ?? "",
                    (next) => updateSelectedStyle({ backgroundColor: next || undefined })
                  )}
                </>
              )}
              {renderFieldGroup(
                t("panel.config.groupBgLayout"),
                <>
                  <label className="block space-y-1" data-config-field="style.backgroundImage">
                    <div>{t("panel.config.backgroundImage")}</div>
                    <Input
                      value={
                        selectedElement.style?.backgroundImageRemoteUrl ??
                        selectedElement.style?.backgroundImage ??
                        ""
                      }
                      onChange={(e) =>
                        updateSelectedStyle(patchBackgroundImageFromInput(e.target.value))
                      }
                      placeholder={t("panel.config.urlScopePlaceholder")}
                      className="h-7 font-mono text-[11px]"
                    />
                    <p className="text-[10px] text-muted-foreground">
                      {t("panel.config.urlScopeHint")}
                    </p>
                  </label>
                  <div className="flex items-center gap-2">
                    <label className="inline-flex cursor-pointer items-center rounded border border-border px-2 py-1 text-[11px] hover:bg-accent">
                      {t("panel.config.uploadImage")}
                      <Input
                        type="file"
                        accept="image/*"
                        className="hidden"
                        onChange={async (e) => {
                          const file = e.target.files?.[0];
                          e.currentTarget.value = "";
                          if (!file) return;
                          await handleUploadBackgroundImage(file);
                        }}
                      />
                    </label>
                    {uploadStatus ? (
                      <span className="text-[11px] text-muted-foreground">{uploadStatus}</span>
                    ) : null}
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                  <label className="block space-y-1">
                    <div>{t("panel.config.backgroundSize")}</div>
                    <Select
                      value={selectedElement.style?.backgroundSize ?? "__none__"}
                      onValueChange={(value) =>
                        updateSelectedStyle({
                          backgroundSize: value === "__none__" ? undefined : value,
                        })
                      }
                    >
                      <SelectTrigger className="h-7">
                        <SelectValue placeholder={t("panel.config.selectBackgroundSize")} />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="__none__">{t("common.default")}</SelectItem>
                        <SelectItem value="cover">cover</SelectItem>
                        <SelectItem value="contain">contain</SelectItem>
                        <SelectItem value="100% 100%">100% 100%</SelectItem>
                        <SelectItem value="auto">auto</SelectItem>
                      </SelectContent>
                    </Select>
                  </label>
                  <label className="block space-y-1">
                    <div>{t("panel.config.backgroundPosition")}</div>
                    <Select
                      value={selectedElement.style?.backgroundPosition ?? "__none__"}
                      onValueChange={(value) =>
                        updateSelectedStyle({
                          backgroundPosition: value === "__none__" ? undefined : value,
                        })
                      }
                    >
                      <SelectTrigger className="h-7">
                        <SelectValue placeholder={t("panel.config.selectBackgroundPosition")} />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="__none__">{t("common.default")}</SelectItem>
                        <SelectItem value="center">center</SelectItem>
                        <SelectItem value="top">top</SelectItem>
                        <SelectItem value="bottom">bottom</SelectItem>
                        <SelectItem value="left">left</SelectItem>
                        <SelectItem value="right">right</SelectItem>
                        <SelectItem value="top left">top left</SelectItem>
                        <SelectItem value="top right">top right</SelectItem>
                        <SelectItem value="bottom left">bottom left</SelectItem>
                        <SelectItem value="bottom right">bottom right</SelectItem>
                      </SelectContent>
                    </Select>
                  </label>
                </div>
                </>,
                undefined,
                { groupKey: "styleBgLayout", defaultOpen: false }
              )}
            </>,
            false,
            [t("panel.config.backgroundColor"), t("panel.config.backgroundImage"), "background", "backgroundSize", "backgroundPosition", t("panel.config.searchKwLayout")]
          )}
          {renderSection(
            "styleBorder",
            t("panel.config.sectionStyleBorder"),
            <>
              {renderFieldGroup(
                t("panel.config.groupBorderGeometry"),
                <div className="grid grid-cols-2 gap-2">
                  <label className="block space-y-1">
                    <div>{t("panel.config.borderWidth")}</div>
                    <Input
                      type="number"
                      min={0}
                      value={selectedElement.style?.borderWidth ?? 0}
                      onChange={(e) =>
                        updateSelectedStyle({ borderWidth: Math.max(0, Number(e.target.value) || 0) })
                      }
                      className="h-7"
                    />
                  </label>
                  <label className="block space-y-1">
                    <div>{t("panel.config.borderRadius")}</div>
                    <Input
                      type="number"
                      min={0}
                      value={selectedElement.style?.borderRadius ?? 0}
                      onChange={(e) =>
                        updateSelectedStyle({ borderRadius: Math.max(0, Number(e.target.value) || 0) })
                      }
                      className="h-7"
                    />
                  </label>
                </div>
              )}
              {renderFieldGroup(
                t("panel.config.groupBorderVisual"),
                <div className="grid grid-cols-2 gap-2">
                  <label className="block space-y-1">
                    <div>{t("panel.config.borderStyle")}</div>
                    <Select
                      value={selectedElement.style?.borderStyle ?? "solid"}
                      onValueChange={(value) =>
                        updateSelectedStyle({
                          borderStyle: value as NonNullable<PanelElementStyle["borderStyle"]>,
                        })
                      }
                    >
                      <SelectTrigger className="h-7">
                        <SelectValue placeholder={t("panel.config.selectBorderStyle")} />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="none">none</SelectItem>
                        <SelectItem value="solid">solid</SelectItem>
                        <SelectItem value="dashed">dashed</SelectItem>
                        <SelectItem value="dotted">dotted</SelectItem>
                        <SelectItem value="double">double</SelectItem>
                      </SelectContent>
                    </Select>
                  </label>
                  {renderColorField(
                    t("panel.config.borderColor"),
                    selectedElement.style?.borderColor ?? "",
                    (next) => updateSelectedStyle({ borderColor: next || undefined })
                  )}
                </div>
              )}
            </>,
            false,
            [t("panel.config.searchKwBorder"), "border", t("panel.config.searchKwWidth"), t("panel.config.searchKwRadius"), t("panel.config.color"), t("panel.config.searchKwStyle")]
          )}
    </>
  );
}

// packages/vue-view/src/panel/components/config/PanelConfigStyleSections.vue
<script setup lang="ts">
import { useI18n } from "@arronqzy/i18n/vue";
import { ref } from "vue";
import { Input, Select } from "ant-design-vue";
import type { PanelElement, PanelElementStyle } from "../../types";
import { readFileAsDataUrl, uploadFileToRemote } from "./shared";
import { patchBackgroundImageFromInput } from "../../utils/background-image-style";
import { getPanelMessages } from "../../constants/messages";
import ConfigColorField from "./ConfigColorField.vue";
import ConfigFieldGroup from "./ConfigFieldGroup.vue";
import ConfigSection from "./ConfigSection.vue";

const { t, locale } = useI18n();
const msgs = () => getPanelMessages(t);

const props = defineProps<{
  element: PanelElement;
  isEditable: boolean;
  backgroundOpen: boolean;
  borderOpen: boolean;
  showBackground?: boolean;
  showBorder?: boolean;
  forceOpen?: boolean;
  updateElement: (
    id: string,
    patch: Partial<PanelElement>,
    options?: { batchId?: string; meta?: Record<string, unknown> }
  ) => void;
}>();

const emit = defineEmits<{
  "update:backgroundOpen": [value: boolean];
  "update:borderOpen": [value: boolean];
}>();

const uploadStatus = ref("");

function patchStyle(patch: Partial<PanelElementStyle>) {
  props.updateElement(props.element.id, {
    style: { ...(props.element.style ?? {}), ...patch },
  });
}

async function handleUploadBackgroundImage(file: File) {
  try {
    const base64 = await readFileAsDataUrl(file, msgs().readImageFailed);
    patchStyle({ backgroundImage: `url("${base64}")` });
    uploadStatus.value = t("panel.config.uploadWrittenBase64");
    const url = await uploadFileToRemote(file);
    if (url) {
      patchStyle({ backgroundImageRemoteUrl: url });
      uploadStatus.value = t("panel.config.uploadServerAndBase64");
    } else {
      uploadStatus.value = t("panel.config.uploadServerFailedKeepBase64");
    }
  } catch (error) {
    uploadStatus.value = error instanceof Error ? error.message : msgs().readImageFailed;
  }
}

function onFileChange(e: Event) {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  input.value = "";
  if (file) void handleUploadBackgroundImage(file);
}
</script>

<template>
  <ConfigSection
    v-if="showBackground !== false"
    :title="t('panel.config.sectionStyleBackground')"
    :open="backgroundOpen"
    :force-open="forceOpen"
    @update:open="emit('update:backgroundOpen', $event)"
  >
    <ConfigFieldGroup :title="t('panel.config.groupBgFill')">
      <ConfigColorField
        :label="t('panel.scope.fieldStyleBackgroundColor')"
        :value="element.style?.backgroundColor ?? ''"
        :disabled="!isEditable"
        @update:value="(v) => patchStyle({ backgroundColor: v || undefined })"
      />
    </ConfigFieldGroup>
    <ConfigFieldGroup
      :title="t('panel.config.groupBgLayout')"
      group-key="styleBgLayout"
      collapsible
      :default-open="false"
    >
      <label class="block space-y-1" data-config-field="style.backgroundImage">
        <div>{{ t("panel.config.backgroundImage") }}</div>
        <Input
          size="small"
          class="font-mono text-[11px]"
          :value="element.style?.backgroundImageRemoteUrl ?? element.style?.backgroundImage ?? ''"
          :disabled="!isEditable"
          :placeholder="t('panel.config.urlScopePlaceholder')"
          @update:value="(v: string) => patchStyle(patchBackgroundImageFromInput(String(v ?? '')))"
        />
        <p class="text-[10px] text-gray-500">{{ t("panel.config.urlScopeHint") }}</p>
      </label>
      <div class="flex items-center gap-2">
        <label
          class="inline-flex cursor-pointer items-center rounded border border-gray-200 px-2 py-1 text-[11px] hover:bg-gray-50"
          :class="{ 'pointer-events-none opacity-50': !isEditable }"
        >
          {{ t("panel.config.uploadImage") }}
          <input
            type="file"
            accept="image/*"
            class="hidden"
            :disabled="!isEditable"
            @change="onFileChange"
          />
        </label>
        <span v-if="uploadStatus" class="text-[11px] text-gray-500">{{ uploadStatus }}</span>
      </div>
      <div class="grid grid-cols-2 gap-2">
        <label class="block space-y-1">
          <div>{{ t("panel.scope.fieldStyleBackgroundSize") }}</div>
          <Select
            size="small"
            class="w-full"
            :value="element.style?.backgroundSize ?? '__none__'"
            :disabled="!isEditable"
            @update:value="(v) => patchStyle({ backgroundSize: v === '__none__' ? undefined : String(v) })"
          >
            <Select.Option value="__none__">{{ t("common.default") }}</Select.Option>
            <Select.Option value="cover">cover</Select.Option>
            <Select.Option value="contain">contain</Select.Option>
            <Select.Option value="100% 100%">100% 100%</Select.Option>
            <Select.Option value="auto">auto</Select.Option>
          </Select>
        </label>
        <label class="block space-y-1">
          <div>{{ t("panel.scope.fieldStyleBackgroundPosition") }}</div>
          <Select
            size="small"
            class="w-full"
            :value="element.style?.backgroundPosition ?? '__none__'"
            :disabled="!isEditable"
            @update:value="(v) => patchStyle({ backgroundPosition: v === '__none__' ? undefined : String(v) })"
          >
            <Select.Option value="__none__">{{ t("common.default") }}</Select.Option>
            <Select.Option value="center">center</Select.Option>
            <Select.Option value="top">top</Select.Option>
            <Select.Option value="bottom">bottom</Select.Option>
            <Select.Option value="left">left</Select.Option>
            <Select.Option value="right">right</Select.Option>
            <Select.Option value="top left">top left</Select.Option>
            <Select.Option value="top right">top right</Select.Option>
            <Select.Option value="bottom left">bottom left</Select.Option>
            <Select.Option value="bottom right">bottom right</Select.Option>
          </Select>
        </label>
      </div>
    </ConfigFieldGroup>
  </ConfigSection>

  <ConfigSection
    v-if="showBorder !== false"
    :title="t('panel.config.sectionStyleBorder')"
    :open="borderOpen"
    :force-open="forceOpen"
    @update:open="emit('update:borderOpen', $event)"
  >
    <ConfigFieldGroup :title="t('panel.config.groupBorderGeometry')">
      <div class="grid grid-cols-2 gap-2">
        <label class="block space-y-1">
          <div>{{ t("panel.config.borderWidth") }}</div>
          <Input
            size="small"
            type="number"
            :min="0"
            :value="String(element.style?.borderWidth ?? 0)"
            :disabled="!isEditable"
            @update:value="(v) => patchStyle({ borderWidth: Math.max(0, Number(v) || 0) })"
          />
        </label>
        <label class="block space-y-1">
          <div>{{ t("panel.config.borderRadius") }}</div>
          <Input
            size="small"
            type="number"
            :min="0"
            :value="String(element.style?.borderRadius ?? 0)"
            :disabled="!isEditable"
            @update:value="(v) => patchStyle({ borderRadius: Math.max(0, Number(v) || 0) })"
          />
        </label>
      </div>
    </ConfigFieldGroup>
    <ConfigFieldGroup :title="t('panel.config.groupBorderVisual')">
      <div class="grid grid-cols-2 gap-2">
        <label class="block space-y-1">
          <div>{{ t("panel.config.borderStyle") }}</div>
          <Select
            size="small"
            class="w-full"
            :value="element.style?.borderStyle ?? 'solid'"
            :disabled="!isEditable"
            @update:value="(v) => patchStyle({ borderStyle: v as PanelElementStyle['borderStyle'] })"
          >
            <Select.Option value="none">none</Select.Option>
            <Select.Option value="solid">solid</Select.Option>
            <Select.Option value="dashed">dashed</Select.Option>
            <Select.Option value="dotted">dotted</Select.Option>
            <Select.Option value="double">double</Select.Option>
          </Select>
        </label>
        <ConfigColorField
          :label="t('panel.scope.fieldStyleBorderColor')"
          :value="element.style?.borderColor ?? ''"
          :disabled="!isEditable"
          @update:value="(v) => patchStyle({ borderColor: v || undefined })"
        />
      </div>
    </ConfigFieldGroup>
  </ConfigSection>
</template>
