// packages/react-view/src/panel/components/config/PanelConfigVideoSection.tsx
import React, { useCallback, useState } from "react";
import { useI18n } from "@arronqzy/i18n/react";
import { Checkbox, Input } from "@arronqzy/ui";
import type { PanelElement } from "../../types";
import { readFileAsDataUrl, runBusyTask } from "../../utils/async-work";
import { getPanelMessages } from "../../constants/messages";
import { ConfigHintIcon } from "../ConfigHintIcon";
import { type ConfigSectionHelpers, type UpdateElement } from "./helpers";

export function PanelConfigVideoSection({
  element,
  helpers,
  updateElement,
}: {
  element: PanelElement;
  helpers: ConfigSectionHelpers;
  updateElement: UpdateElement;
}) {
  const { t } = useI18n();
  const messages = React.useMemo(() => getPanelMessages(t), [t]);
  const { renderSection, renderFieldGroup } = helpers;
  const selectedElement = element;
  const [videoStatus, setVideoStatus] = useState("");

  const updateSelectedVideo = useCallback(
    (patch: Partial<PanelElement>) => {
      if (selectedElement.materialType !== "video") return;
      updateElement(selectedElement.id, patch);
    },
    [selectedElement, updateElement]
  );
  const handleUploadVideoFile = useCallback(
    async (file: File) => {
      if (selectedElement.materialType !== "video") return;
      try {
        await runBusyTask(t("common.uploadingFile"), async () => {
          const base64 = await readFileAsDataUrl(file, messages.readVideoFailed, "video");
          updateSelectedVideo({ videoSrc: base64 });
          setVideoStatus(messages.videoLocalSaved);
          try {
            const form = new FormData();
            form.append("file", file);
            const resp = await fetch("/api/upload", { method: "POST", body: form });
            if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
            const data = (await resp.json()) as { url?: string };
            if (data.url) {
              updateSelectedVideo({ videoRemoteUrl: data.url });
              setVideoStatus(messages.videoRemoteUploaded);
            }
          } catch {
            setVideoStatus(messages.videoServerUploadFailed);
          }
        });
      } catch (error) {
        setVideoStatus(
          error instanceof Error ? error.message : messages.readVideoFailed
        );
      }
    },
    [messages, selectedElement, t, updateSelectedVideo]
  );

  return (
    <>
      {
            renderSection(
              "videoConfig",
              t("panel.config.sectionVideo"),
              <>
                {renderFieldGroup(
                  t("panel.config.groupVideoSource"),
                  <>
                    <label className="block space-y-1" data-config-field="videoRemoteUrl">
                      <div className="flex items-center gap-1">
                        {t("panel.config.videoUrl")}
                        <ConfigHintIcon label={t("panel.config.videoUrl")}>
                          {t("panel.config.urlScopeHint")}
                        </ConfigHintIcon>
                      </div>
                      <Input
                        value={selectedElement.videoRemoteUrl ?? ""}
                        onChange={(e) =>
                          updateSelectedVideo({
                            videoRemoteUrl: e.target.value || undefined,
                            videoSrc: e.target.value || selectedElement.videoSrc,
                          })
                        }
                        placeholder={t("panel.config.urlScopePlaceholder")}
                        className="h-7 font-mono text-[11px]"
                      />
                    </label>
                    <div className="flex items-center gap-2">
                      <label className="inline-flex cursor-pointer items-center rounded border border-border px-2 py-1 text-[11px] hover:bg-accent">
                        {t("panel.config.uploadVideo")}
                        <Input
                          type="file"
                          accept="video/*"
                          className="hidden"
                          onChange={async (e) => {
                            const file = e.target.files?.[0];
                            e.currentTarget.value = "";
                            if (!file) return;
                            await handleUploadVideoFile(file);
                          }}
                        />
                      </label>
                    </div>
                    {videoStatus ? (
                      <div className="rounded border border-border/60 bg-background px-2 py-1.5 text-[11px] text-muted-foreground">
                        {videoStatus}
                      </div>
                    ) : null}
                    <video
                      controls
                      className="h-36 w-full rounded border border-border/60 bg-black/80 object-contain"
                      src={selectedElement.videoSrc || selectedElement.videoRemoteUrl || ""}
                    />
                    <label className="flex items-center gap-2">
                      <Checkbox
                        checked={selectedElement.mediaAutoPauseOnEdit !== false}
                        className="h-4 w-4 border-2 border-foreground/80 bg-background ring-1 ring-foreground/40 data-[state=checked]:border-primary data-[state=checked]:ring-primary/40"
                        onCheckedChange={(checked) =>
                          updateSelectedVideo({
                            mediaAutoPauseOnEdit: checked !== false,
                          })
                        }
                      />
                      <span>{t("panel.config.autoPauseMedia")}</span>
                    </label>
                  </>
                )}
              </>,
              true,
              [t("panel.material.video"), "url", t("panel.config.searchKwUpload"), t("panel.config.searchKwPreview"), t("panel.config.searchKwAutoPause"), "media"]
            )
      }
    </>
  );
}

// packages/vue-view/src/panel/components/config/PanelConfigVideoSection.vue
<script setup lang="ts">
import { useI18n } from "@arronqzy/i18n/vue";
import { ref } from "vue";
import { Checkbox, Input } from "ant-design-vue";
import type { PanelElement } from "../../types";
import { readFileAsDataUrl, uploadFileToRemote } from "./shared";
import { getPanelMessages } from "../../constants/messages";
import ConfigFieldGroup from "./ConfigFieldGroup.vue";
import ConfigSection from "./ConfigSection.vue";
import ConfigHintIcon from "../ConfigHintIcon.vue";

const { t, locale } = useI18n();
const msgs = () => getPanelMessages(t);

const props = defineProps<{
  element: PanelElement;
  isEditable: boolean;
  open: boolean;
  forceOpen?: boolean;
  updateElement: (
    id: string,
    patch: Partial<PanelElement>,
    options?: { batchId?: string; meta?: Record<string, unknown> }
  ) => void;
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
}>();

const videoStatus = ref("");

function patch(patch: Partial<PanelElement>) {
  if (props.element.materialType !== "video") return;
  props.updateElement(props.element.id, patch);
}

async function handleUploadVideoFile(file: File) {
  try {
    const base64 = await readFileAsDataUrl(file, msgs().readVideoFailed, "video");
    patch({ videoSrc: base64 });
    videoStatus.value = msgs().videoLocalSaved;
    const url = await uploadFileToRemote(file);
    if (url) {
      patch({ videoRemoteUrl: url });
      videoStatus.value = msgs().videoRemoteUploaded;
    } else {
      videoStatus.value = msgs().videoServerUploadFailed;
    }
  } catch (error) {
    videoStatus.value = error instanceof Error ? error.message : msgs().readVideoFailed;
  }
}

function onVideoFileChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  (e.target as HTMLInputElement).value = "";
  if (file) void handleUploadVideoFile(file);
}
</script>

<template>
  <ConfigSection
    :title="t('panel.config.sectionVideo')"
    :open="open"
    :force-open="forceOpen"
    @update:open="emit('update:open', $event)"
  >
    <ConfigFieldGroup :title="t('panel.config.groupVideoSource')">
      <label class="block space-y-1" data-config-field="videoRemoteUrl">
        <div class="flex items-center gap-1">
          {{ t("panel.config.videoUrl") }}
          <ConfigHintIcon :label="t('panel.config.videoUrl')">
            {{ t("panel.config.urlScopeHint") }}
          </ConfigHintIcon>
        </div>
        <Input
          size="small"
          class="font-mono text-[11px]"
          :value="element.videoRemoteUrl ?? ''"
          :disabled="!isEditable"
          :placeholder="t('panel.config.urlScopePlaceholder')"
          @update:value="(v: string) => patch({
            videoRemoteUrl: v || undefined,
            videoSrc: v || element.videoSrc,
          })"
        />      </label>
      <div class="flex items-center gap-2">
        <label
          class="inline-flex cursor-pointer items-center rounded border border-gray-200 px-2 py-1 text-[11px] hover:bg-gray-50"
          :class="{ 'pointer-events-none opacity-50': !isEditable }"
        >
          {{ t("panel.config.uploadVideo") }}
          <input type="file" accept="video/*" class="hidden" :disabled="!isEditable" @change="onVideoFileChange" />
        </label>
      </div>
      <div
        v-if="videoStatus"
        class="rounded border border-gray-200/60 bg-white px-2 py-1.5 text-[11px] text-gray-500"
      >
        {{ videoStatus }}
      </div>
      <video
        controls
        class="h-36 w-full rounded border border-gray-200/60 bg-black/80 object-contain"
        :src="element.videoSrc || element.videoRemoteUrl || ''"
      />
      <label class="flex items-center gap-2">
        <Checkbox
          :checked="element.mediaAutoPauseOnEdit !== false"
          :disabled="!isEditable"
          @update:checked="(v) => patch({ mediaAutoPauseOnEdit: v !== false })"
        />
        <span>{{ t("panel.config.autoPauseMedia") }}</span>
      </label>
    </ConfigFieldGroup>
  </ConfigSection>
</template>
