// packages/react-view/src/panel/components/config/PanelConfigGridSection.tsx
import { useI18n } from "@arronqzy/i18n/react";
import { Input } from "@arronqzy/ui";
import type { PanelElement } from "../../types";
import { type ConfigSectionHelpers, type UpdateElement } from "./helpers";

export function PanelConfigGridSection({
  element,
  helpers,
  updateElement,
}: {
  element: PanelElement;
  helpers: ConfigSectionHelpers;
  updateElement: UpdateElement;
}) {
  const { t } = useI18n();
  const { renderSection, renderFieldGroup } = helpers;
  const selectedElement = element;
  return (
    <>
      {
            renderSection(
              "gridConfig",
              t("panel.config.sectionGrid"),
              <>
                {renderFieldGroup(
                  t("panel.config.groupGridParams"),
                  <div className="grid grid-cols-2 gap-2">
                    <label className="block space-y-1">
                      <div>{t("panel.config.rowCount")}</div>
                      <Input
                        type="number"
                        min={1}
                        max={12}
                        value={selectedElement.gridRows ?? 2}
                        onChange={(e) =>
                          updateElement(selectedElement.id, {
                            gridRows: Math.max(1, Math.min(12, Number(e.target.value) || 2)),
                          })
                        }
                        className="h-7"
                      />
                    </label>
                    <label className="block space-y-1">
                      <div>{t("panel.config.colCount")}</div>
                      <Input
                        type="number"
                        min={1}
                        max={12}
                        value={selectedElement.gridCols ?? 3}
                        onChange={(e) =>
                          updateElement(selectedElement.id, {
                            gridCols: Math.max(1, Math.min(12, Number(e.target.value) || 3)),
                          })
                        }
                        className="h-7"
                      />
                    </label>
                    <label className="block space-y-1">
                      <div>{t("panel.config.gapPx")}</div>
                      <Input
                        type="number"
                        min={0}
                        max={80}
                        value={selectedElement.gridGap ?? 8}
                        onChange={(e) =>
                          updateElement(selectedElement.id, {
                            gridGap: Math.max(0, Math.min(80, Number(e.target.value) || 0)),
                          })
                        }
                        className="h-7"
                      />
                    </label>
                    <label className="block space-y-1">
                      <div>{t("panel.config.paddingPx")}</div>
                      <Input
                        type="number"
                        min={0}
                        max={100}
                        value={selectedElement.gridPadding ?? 10}
                        onChange={(e) =>
                          updateElement(selectedElement.id, {
                            gridPadding: Math.max(0, Math.min(100, Number(e.target.value) || 0)),
                          })
                        }
                        className="h-7"
                      />
                    </label>
                    <label className="block space-y-1">
                      <div>{t("panel.config.snapThresholdPx")}</div>
                      <Input
                        type="number"
                        min={8}
                        max={120}
                        value={selectedElement.gridSnapThreshold ?? 36}
                        onChange={(e) =>
                          updateElement(selectedElement.id, {
                            gridSnapThreshold: Math.max(
                              8,
                              Math.min(120, Number(e.target.value) || 36)
                            ),
                          })
                        }
                        className="h-7"
                      />
                    </label>
                  </div>
                )}
              </>,
              true,
              [t("panel.config.searchKwGrid"), "grid", t("panel.config.rows"), t("panel.config.cols"), t("panel.config.searchKwGap"), t("panel.config.searchKwPadding"), t("panel.config.searchKwSnap"), t("panel.config.searchKwThreshold")],
              <>
                {t("panel.config.gridHint")}
              </>
            )
      }
    </>
  );
}

// packages/vue-view/src/panel/components/config/PanelConfigGridSection.vue
<script setup lang="ts">
import { useI18n } from "@arronqzy/i18n/vue";
import { InputNumber } from "ant-design-vue";
import type { PanelElement } from "../../types";
import ConfigFieldGroup from "./ConfigFieldGroup.vue";
import ConfigSection from "./ConfigSection.vue";

const { t, locale } = useI18n();
const props = defineProps<{
  element: PanelElement;
  isEditable: boolean;
  open: boolean;
  forceOpen?: boolean;
  updateElement: (
    id: string,
    patch: Partial<PanelElement>,
    options?: { batchId?: string; meta?: Record<string, unknown> }
  ) => void;
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
}>();

function patch(patch: Partial<PanelElement>) {
  props.updateElement(props.element.id, patch);
}
</script>

<template>
  <ConfigSection
    :title="t('panel.config.sectionGrid')"
    :open="open"
    :force-open="forceOpen"
    @update:open="emit('update:open', $event)"
  >
    <template #hint>
      {{ t("panel.config.gridHint") }}
    </template>
    <ConfigFieldGroup :title="t('panel.config.groupGridParams')">
      <div class="grid grid-cols-2 gap-2">
        <label class="block space-y-1">
          <div>{{ t("panel.config.rowCount") }}</div>
          <InputNumber
            size="small"
            class="w-full"
            :min="1"
            :max="12"
            :value="element.gridRows ?? 2"
            :disabled="!isEditable"
            @update:value="(v) => { const n = Number(v); if (!Number.isNaN(n)) patch({ gridRows: Math.max(1, Math.min(12, n)) }); }"
          />
        </label>
        <label class="block space-y-1">
          <div>{{ t("panel.config.colCount") }}</div>
          <InputNumber
            size="small"
            class="w-full"
            :min="1"
            :max="12"
            :value="element.gridCols ?? 3"
            :disabled="!isEditable"
            @update:value="(v) => { const n = Number(v); if (!Number.isNaN(n)) patch({ gridCols: Math.max(1, Math.min(12, n)) }); }"
          />
        </label>
        <label class="block space-y-1">
          <div>{{ t("panel.config.gapPx") }}</div>
          <InputNumber
            size="small"
            class="w-full"
            :min="0"
            :max="80"
            :value="element.gridGap ?? 8"
            :disabled="!isEditable"
            @update:value="(v) => { const n = Number(v); if (!Number.isNaN(n)) patch({ gridGap: Math.max(0, Math.min(80, n)) }); }"
          />
        </label>
        <label class="block space-y-1">
          <div>{{ t("panel.config.paddingPx") }}</div>
          <InputNumber
            size="small"
            class="w-full"
            :min="0"
            :max="100"
            :value="element.gridPadding ?? 10"
            :disabled="!isEditable"
            @update:value="(v) => { const n = Number(v); if (!Number.isNaN(n)) patch({ gridPadding: Math.max(0, Math.min(100, n)) }); }"
          />
        </label>
        <label class="block space-y-1">
          <div>{{ t("panel.config.snapThresholdPx") }}</div>
          <InputNumber
            size="small"
            class="w-full"
            :min="8"
            :max="120"
            :value="element.gridSnapThreshold ?? 36"
            :disabled="!isEditable"
            @update:value="(v) => { const n = Number(v); if (!Number.isNaN(n)) patch({ gridSnapThreshold: Math.max(8, Math.min(120, n)) }); }"
          />
        </label>
      </div>
    </ConfigFieldGroup>
  </ConfigSection>
</template>
