// packages/vue-blueprint/src/edges/BlueprintSmoothEdge.vue
<script setup lang="ts">
import { BaseEdge, getSmoothStepPath, type EdgeProps } from "@vue-flow/core";
import { computed } from "vue";

const EDGE_STROKE = "#94a3b8";
const EDGE_WIDTH = 1.75;

const props = defineProps<EdgeProps>();

const path = computed(() => {
  const [edgePath] = getSmoothStepPath({
    sourceX: props.sourceX,
    sourceY: props.sourceY,
    sourcePosition: props.sourcePosition,
    targetX: props.targetX,
    targetY: props.targetY,
    targetPosition: props.targetPosition,
  });
  return edgePath;
});

const edgeStyle = computed(() => ({
  stroke: EDGE_STROKE,
  strokeWidth: EDGE_WIDTH,
  ...(props.style as Record<string, unknown> | undefined),
}));
</script>

<template>
  <BaseEdge :path="path" class="bp-edge-visible" :style="edgeStyle" />
</template>

// packages/react-blueprint/src/edges/BlueprintSmoothEdge.tsx
import { BaseEdge, getSmoothStepPath, type EdgeProps } from "@xyflow/react";

const EDGE_STROKE = "#94a3b8";
const EDGE_WIDTH = 1.75;

export function BlueprintSmoothEdge({
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  style,
}: EdgeProps) {
  const [path] = getSmoothStepPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });

  return (
    <BaseEdge
      path={path}
      className="bp-edge-visible"
      style={{
        stroke: EDGE_STROKE,
        strokeWidth: EDGE_WIDTH,
        ...style,
      }}
    />
  );
}
