// packages/vue-view/src/panel/components/table/TableNodeContent.vue
<script setup lang="ts">
import { computed, defineComponent, h, ref, type PropType, type VNode } from "vue";
import { useVirtualizer } from "@tanstack/vue-virtual";
import { useI18n } from "@arronqzy/i18n/vue";
import {
  transformToTableCached,
  resolveCellDisplay,
  resolveRowDisplay,
  stylePropsToCss,
  resolveRawTableInput,
  resolveProgressDisplay,
  type PanelTableConfig,
  type NormalizedColumn,
  type NormalizedRow,
  type CellDisplay,
  type TableCellActionPayload,
} from "@arronqzy/view-table";
import type { PanelElement } from "../../types";

export type TableCellActionHandler = (payload: TableCellActionPayload) => void;

const props = withDefaults(
  defineProps<{
    element: PanelElement;
    interactive?: boolean;
    onCellAction?: TableCellActionHandler;
  }>(),
  { interactive: false }
);

const { t } = useI18n();
const parentRef = ref<HTMLDivElement | null>(null);

const config = computed(
  () => (props.element.table ?? {}) as PanelTableConfig
);

const model = computed(() => {
  const raw = resolveRawTableInput(config.value);
  return transformToTableCached(raw, config.value);
});

const columns = computed(() => model.value.columns);
const rowHeight = computed(() => Math.max(24, config.value.rowHeight ?? 36));
const showHeader = computed(() => config.value.showHeader !== false);
const emptyText = computed(
  () => config.value.emptyText || t("panel.config.tableEmpty")
);

const gridTemplate = computed(() =>
  columns.value
    .map((c) => {
      if (c.width) return `${c.width}px`;
      if (c.minWidth) return `minmax(${c.minWidth}px, 1fr)`;
      return "minmax(96px, 1fr)";
    })
    .join(" ")
);

const virtualizerOptions = computed(() => ({
  count: model.value.rows.length,
  getScrollElement: () => parentRef.value,
  estimateSize: () => rowHeight.value,
  overscan: 8,
}));

const virtualizer = useVirtualizer(virtualizerOptions);
const virtualItems = computed(() => virtualizer.value.getVirtualItems());
const totalSize = computed(() => virtualizer.value.getTotalSize());

const tableStyle = computed(() => stylePropsToCss(config.value.tableStyle ?? {}));
const headerStyle = computed(() => stylePropsToCss(config.value.headerStyle ?? {}));

const tableTextColor = computed(
  () =>
    (typeof tableStyle.value.color === "string" && tableStyle.value.color.trim()) ||
    (typeof config.value.tableStyle?.color === "string" && config.value.tableStyle.color.trim()) ||
    "#111827"
);
const headerTextColor = computed(
  () =>
    (typeof headerStyle.value.color === "string" && headerStyle.value.color.trim()) ||
    (typeof config.value.headerStyle?.color === "string" && config.value.headerStyle.color.trim()) ||
    tableTextColor.value
);

const rootStyle = computed(() => ({
  background: (config.value.tableStyle?.backgroundColor as string) || "#fff",
  border:
    config.value.tableStyle?.borderWidth != null
      ? `${config.value.tableStyle.borderWidth}px solid ${config.value.tableStyle.borderColor ?? "rgba(0,0,0,0.12)"}`
      : "1px solid rgba(0,0,0,0.08)",
  borderRadius: config.value.tableStyle?.borderRadius ?? 6,
  fontSize: config.value.tableStyle?.fontSize ?? 12,
  ...tableStyle.value,
  color: tableTextColor.value,
  display: "flex" as const,
  flexDirection: "column" as const,
}));

const headerRowStyle = computed(() => ({
  display: "grid" as const,
  gridTemplateColumns: gridTemplate.value,
  height: `${rowHeight.value}px`,
  flex: "0 0 auto",
  position:
    config.value.tableStyle?.stickyHeader === false
      ? ("relative" as const)
      : ("sticky" as const),
  top: 0,
  zIndex: 2,
  background: (config.value.headerStyle?.backgroundColor as string) || "rgba(0,0,0,0.04)",
  borderBottom: "1px solid rgba(0,0,0,0.1)",
  ...headerStyle.value,
  color: headerTextColor.value,
}));

function headerLabelOf(col: NormalizedColumn) {
  return (col.title ?? "").trim() || col.field || col.id;
}

function headerJustify(align: NormalizedColumn["align"]) {
  if (align === "center") return "center";
  if (align === "right") return "flex-end";
  return "flex-start";
}

function cellCommonStyle(cell: CellDisplay): Record<string, string | number> {
  const style = stylePropsToCss(cell.style);
  const textOverflow = cell.widgetProps?.textStyle?.overflow ?? "ellipsis";
  const isWrap = cell.widget === "text" && textOverflow === "wrap";
  return {
    ...style,
    overflow: "hidden",
    ...(isWrap
      ? { whiteSpace: "normal", wordBreak: "break-word" }
      : { textOverflow: "ellipsis", whiteSpace: "nowrap" }),
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: isWrap ? "flex-start" : "center",
    boxSizing: "border-box",
    padding: (style.padding as string | number | undefined) ?? "0 8px",
  };
}

const TableCellView = defineComponent({
  name: "TableCellView",
  props: {
    cell: { type: Object as PropType<CellDisplay>, required: true },
    row: { type: Object as PropType<NormalizedRow>, required: true },
    column: { type: Object as PropType<NormalizedColumn>, required: true },
    elementId: { type: String, required: true },
    interactive: { type: Boolean, default: false },
    onCellAction: { type: Function as PropType<TableCellActionHandler | undefined>, default: undefined },
  },
  setup(p) {
    const emit = (kind: TableCellActionPayload["kind"], blueprintNodeId?: string) => {
      const id = blueprintNodeId?.trim();
      if (!id || !p.onCellAction) return;
      p.onCellAction({
        kind,
        blueprintNodeId: id,
        elementId: p.elementId,
        columnField: p.column.field,
        rowId: p.row.id,
        row: p.row.values,
        value: p.cell.raw,
      });
    };

    return (): VNode => {
      const cell = p.cell;
      const common = cellCommonStyle(cell);

      if (cell.widget === "tag" || cell.widget === "badge") {
        const bg = cell.color ?? "#3b82f6";
        return h("div", { style: common }, [
          h(
            "span",
            {
              style: {
                display: "inline-flex",
                alignItems: "center",
                gap: 6,
                maxWidth: "100%",
                borderRadius: cell.widget === "badge" ? 999 : 4,
                padding: cell.widget === "badge" ? "0 8px" : "1px 8px",
                fontSize: 12,
                lineHeight: "20px",
                color: "#fff",
                background: bg,
              },
            },
            [
              cell.widget === "badge"
                ? h("span", {
                    style: {
                      width: 6,
                      height: 6,
                      borderRadius: 99,
                      background: "rgba(255,255,255,0.9)",
                      flex: "0 0 auto",
                    },
                  })
                : null,
              h("span", { style: { overflow: "hidden", textOverflow: "ellipsis" } }, cell.text),
            ]
          ),
        ]);
      }

      if (cell.widget === "link") {
        return h("div", { style: common }, [
          h(
            "a",
            {
              href: cell.href || "#",
              target: cell.widgetProps?.openInNewTab === false ? undefined : "_blank",
              rel: "noreferrer",
              onClick: (e: Event) => {
                e.stopPropagation();
                emit("click", cell.widgetProps?.actions?.onClickBlueprintNodeId);
              },
              style: {
                color: "#2563eb",
                textDecoration: "underline",
                overflow: "hidden",
                textOverflow: "ellipsis",
              },
            },
            cell.text || cell.href
          ),
        ]);
      }

      if (cell.widget === "progress") {
        const pct = cell.progress ?? 0;
        const display = resolveProgressDisplay(cell.widgetProps);
        const trackColor = cell.color ?? "#3b82f6";
        const label = h(
          "span",
          { style: { fontSize: 11, color: "rgba(0,0,0,0.55)", flex: "0 0 auto" } },
          `${Math.round(pct)}%`
        );

        if (display === "label") {
          return h("div", { style: common }, [label]);
        }

        if (display === "circle") {
          const size = Math.max(16, cell.widgetProps?.progressSize ?? 28);
          const stroke = Math.max(2, cell.widgetProps?.progressStrokeWidth ?? 3);
          const r = (size - stroke) / 2;
          const c = 2 * Math.PI * r;
          const offset = c * (1 - Math.max(0, Math.min(100, pct)) / 100);
          return h("div", { style: { ...common, gap: 6, justifyContent: "center" } }, [
            h("svg", { width: size, height: size, style: { flex: "0 0 auto" } }, [
              h("circle", {
                cx: size / 2,
                cy: size / 2,
                r,
                fill: "none",
                stroke: "rgba(0,0,0,0.08)",
                "stroke-width": stroke,
              }),
              h("circle", {
                cx: size / 2,
                cy: size / 2,
                r,
                fill: "none",
                stroke: trackColor,
                "stroke-width": stroke,
                "stroke-linecap": "round",
                "stroke-dasharray": c,
                "stroke-dashoffset": offset,
                transform: `rotate(-90 ${size / 2} ${size / 2})`,
              }),
              h(
                "text",
                {
                  x: "50%",
                  y: "50%",
                  "dominant-baseline": "central",
                  "text-anchor": "middle",
                  "font-size": Math.max(8, Math.round(size * 0.32)),
                  fill: "rgba(0,0,0,0.65)",
                },
                String(Math.round(pct))
              ),
            ]),
          ]);
        }

        const bar = h(
          "div",
          {
            style: {
              flex: 1,
              height: 8,
              borderRadius: 99,
              background: "rgba(0,0,0,0.08)",
              overflow: "hidden",
              minWidth: 24,
            },
          },
          [
            h("div", {
              style: { width: `${pct}%`, height: "100%", background: trackColor },
            }),
          ]
        );

        return h("div", { style: { ...common, gap: 8 } }, [
          bar,
          display === "barLabel" ? label : null,
        ]);
      }

      if (cell.widget === "image") {
        const w = cell.widgetProps?.imageWidth ?? 28;
        const hImg = cell.widgetProps?.imageHeight ?? 28;
        return h("div", { style: common }, [
          cell.imageUrl
            ? h("img", {
                src: cell.imageUrl,
                alt: "",
                style: {
                  width: w,
                  height: hImg,
                  objectFit: (cell.widgetProps?.imageObjectFit as string) || "cover",
                  borderRadius: 4,
                },
                draggable: false,
              })
            : h("span", { style: { fontSize: 11, opacity: 0.5 } }, "—"),
        ]);
      }

      if (cell.widget === "boolean") {
        const on = Boolean(cell.booleanValue);
        const canToggle = Boolean(p.interactive && p.onCellAction);
        return h("div", { style: common }, [
          h(
            "button",
            {
              type: "button",
              disabled: !canToggle,
              onMousedown: (e: Event) => e.stopPropagation(),
              onClick: (e: Event) => {
                e.stopPropagation();
                if (!canToggle) return;
                if (on) {
                  emit("toggleOff", cell.widgetProps?.actions?.onFalseBlueprintNodeId);
                } else {
                  emit("toggleOn", cell.widgetProps?.actions?.onTrueBlueprintNodeId);
                }
              },
              style: {
                width: 28,
                height: 16,
                borderRadius: 99,
                background: on ? "#16a34a" : "rgba(0,0,0,0.2)",
                position: "relative",
                display: "inline-block",
                flex: "0 0 auto",
                border: "none",
                padding: 0,
                cursor: canToggle ? "pointer" : "default",
              },
              "aria-pressed": on,
            },
            [
              h("span", {
                style: {
                  position: "absolute",
                  top: 2,
                  left: on ? 14 : 2,
                  width: 12,
                  height: 12,
                  borderRadius: 99,
                  background: "#fff",
                },
              }),
            ]
          ),
          h("span", { style: { marginLeft: 6, fontSize: 12 } }, cell.text),
        ]);
      }

      const textStyle = cell.widgetProps?.textStyle;
      const canClickText = Boolean(cell.widgetProps?.actions?.onClickBlueprintNodeId);
      return h(
        "div",
        {
          style: {
            ...common,
            fontFamily: textStyle?.fontFamily,
            fontStyle: textStyle?.fontStyle,
            textDecoration:
              textStyle?.textDecoration === "none" ? undefined : textStyle?.textDecoration,
            cursor: canClickText ? "pointer" : undefined,
            color: canClickText && !(common as { color?: string }).color ? "#2563eb" : common.color,
          },
          title: cell.text,
          onClick: (e: Event) => {
            if (!canClickText) return;
            e.stopPropagation();
            emit("click", cell.widgetProps?.actions?.onClickBlueprintNodeId);
          },
        },
        cell.text
      );
    };
  },
});

const TableRowView = defineComponent({
  name: "TableRowView",
  props: {
    row: { type: Object as PropType<NormalizedRow>, required: true },
    columns: { type: Array as PropType<NormalizedColumn[]>, required: true },
    config: { type: Object as PropType<PanelTableConfig>, required: true },
    rowHeight: { type: Number, required: true },
    gridTemplate: { type: String, required: true },
    elementId: { type: String, required: true },
    interactive: { type: Boolean, default: false },
    onCellAction: { type: Function as PropType<TableCellActionHandler | undefined>, default: undefined },
  },
  setup(p) {
    return (): VNode => {
      const rowDisplay = resolveRowDisplay(p.row, p.config);
      return h(
        "div",
        {
          role: "row",
          style: {
            display: "grid",
            gridTemplateColumns: p.gridTemplate,
            height: p.rowHeight,
            boxSizing: "border-box",
            borderBottom: "1px solid rgba(0,0,0,0.06)",
            ...stylePropsToCss(rowDisplay.style),
          },
        },
        p.columns.map((col) => {
          const cell = resolveCellDisplay(p.row, col, p.config);
          return h(
            "div",
            {
              key: col.id,
              role: "cell",
              style: { minWidth: 0, borderRight: "1px solid rgba(0,0,0,0.04)" },
            },
            [
              h(TableCellView, {
                cell,
                row: p.row,
                column: col,
                elementId: p.elementId,
                interactive: p.interactive,
                onCellAction: p.onCellAction,
              }),
            ]
          );
        })
      );
    };
  },
});
</script>

<template>
  <div class="rv-table-node h-full w-full overflow-hidden" :style="rootStyle">
    <div v-if="showHeader" role="row" :style="headerRowStyle">
      <div
        v-for="col in columns"
        :key="col.id"
        role="columnheader"
        :title="headerLabelOf(col)"
        :style="{
          padding: '0 8px',
          display: 'flex',
          alignItems: 'center',
          fontWeight: config.headerStyle?.fontWeight ?? 600,
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          borderRight: '1px solid rgba(0,0,0,0.04)',
          textAlign: col.align,
          justifyContent: headerJustify(col.align),
        }"
      >
        {{ headerLabelOf(col) }}
      </div>
    </div>

    <div ref="parentRef" class="min-h-0 flex-1 overflow-auto">
      <div
        v-if="model.rows.length === 0"
        class="flex h-full flex-col items-center justify-center gap-2 px-3 text-center text-xs text-gray-400"
      >
        <svg
          viewBox="0 0 48 48"
          class="h-10 w-10 opacity-45"
          fill="none"
          stroke="currentColor"
          stroke-width="1.6"
          aria-hidden="true"
        >
          <rect x="8" y="12" width="32" height="24" rx="3" />
          <path d="M8 20h32M20 12v24M28 12v24" stroke-opacity="0.55" />
          <circle cx="24" cy="30" r="1.2" fill="currentColor" stroke="none" />
        </svg>
        <div>{{ emptyText }}</div>
      </div>
      <div
        v-else
        :style="{ height: `${totalSize}px`, position: 'relative', width: '100%' }"
      >
        <div
          v-for="item in virtualItems"
          :key="model.rows[item.index]?.id ?? item.key"
          :style="{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: `${item.size}px`,
            transform: `translateY(${item.start}px)`,
          }"
        >
          <TableRowView
            v-if="model.rows[item.index]"
            :row="model.rows[item.index]!"
            :columns="columns"
            :config="config"
            :row-height="rowHeight"
            :grid-template="gridTemplate"
            :element-id="element.id"
            :interactive="interactive"
            :on-cell-action="onCellAction"
          />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/react-view/src/panel/components/table/TableNodeContent.tsx
import React, { useMemo, useRef } from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import {
  transformToTableCached,
  resolveCellDisplay,
  resolveRowDisplay,
  stylePropsToCss,
  resolveRawTableInput,
  resolveProgressDisplay,
  type PanelTableConfig,
  type NormalizedColumn,
  type NormalizedRow,
  type CellDisplay,
  type TableCellActionPayload,
} from "@arronqzy/view-table";
import type { PanelElement } from "../../types";
import { useI18n } from "@arronqzy/i18n/react";

export type TableCellActionHandler = (payload: TableCellActionPayload) => void;

function TableCellView({
  cell,
  row,
  column,
  elementId,
  interactive,
  onCellAction,
}: {
  cell: CellDisplay;
  row: NormalizedRow;
  column: NormalizedColumn;
  elementId: string;
  interactive?: boolean;
  onCellAction?: TableCellActionHandler;
}) {
  const emit = (kind: TableCellActionPayload["kind"], blueprintNodeId?: string) => {
    const id = blueprintNodeId?.trim();
    if (!id || !onCellAction) return;
    onCellAction({
      kind,
      blueprintNodeId: id,
      elementId,
      columnField: column.field,
      rowId: row.id,
      row: row.values,
      value: cell.raw,
    });
  };

  const style = stylePropsToCss(cell.style);
  const textOverflow = cell.widgetProps?.textStyle?.overflow ?? "ellipsis";
  const isWrap = cell.widget === "text" && textOverflow === "wrap";
  const common: React.CSSProperties = {
    ...style,
    overflow: "hidden",
    textOverflow: isWrap ? undefined : "ellipsis",
    whiteSpace: isWrap ? "normal" : "nowrap",
    wordBreak: isWrap ? "break-word" : undefined,
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: isWrap ? "flex-start" : "center",
    boxSizing: "border-box",
    padding: style.padding ?? "0 8px",
  };

  if (cell.widget === "tag" || cell.widget === "badge") {
    const bg = cell.color ?? "#3b82f6";
    return (
      <div style={common}>
        <span
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 6,
            maxWidth: "100%",
            borderRadius: cell.widget === "badge" ? 999 : 4,
            padding: cell.widget === "badge" ? "0 8px" : "1px 8px",
            fontSize: 12,
            lineHeight: "20px",
            color: "#fff",
            background: bg,
          }}
        >
          {cell.widget === "badge" ? (
            <span
              style={{
                width: 6,
                height: 6,
                borderRadius: 99,
                background: "rgba(255,255,255,0.9)",
                flex: "0 0 auto",
              }}
            />
          ) : null}
          <span style={{ overflow: "hidden", textOverflow: "ellipsis" }}>{cell.text}</span>
        </span>
      </div>
    );
  }

  if (cell.widget === "link") {
    return (
      <div style={common}>
        <a
          href={cell.href || "#"}
          target={cell.widgetProps?.openInNewTab === false ? undefined : "_blank"}
          rel="noreferrer"
          onClick={(e) => {
            e.stopPropagation();
            emit("click", cell.widgetProps?.actions?.onClickBlueprintNodeId);
          }}
          style={{ color: "#2563eb", textDecoration: "underline", overflow: "hidden", textOverflow: "ellipsis" }}
        >
          {cell.text || cell.href}
        </a>
      </div>
    );
  }

  if (cell.widget === "progress") {
    const pct = cell.progress ?? 0;
    const display = resolveProgressDisplay(cell.widgetProps);
    const trackColor = cell.color ?? "#3b82f6";
    const label = (
      <span style={{ fontSize: 11, color: "rgba(0,0,0,0.55)", flex: "0 0 auto" }}>
        {Math.round(pct)}%
      </span>
    );

    if (display === "label") {
      return <div style={common}>{label}</div>;
    }

    if (display === "circle") {
      const size = Math.max(16, cell.widgetProps?.progressSize ?? 28);
      const stroke = Math.max(2, cell.widgetProps?.progressStrokeWidth ?? 3);
      const r = (size - stroke) / 2;
      const c = 2 * Math.PI * r;
      const offset = c * (1 - Math.max(0, Math.min(100, pct)) / 100);
      return (
        <div style={{ ...common, gap: 6, justifyContent: "center" }}>
          <svg width={size} height={size} style={{ flex: "0 0 auto" }}>
            <circle
              cx={size / 2}
              cy={size / 2}
              r={r}
              fill="none"
              stroke="rgba(0,0,0,0.08)"
              strokeWidth={stroke}
            />
            <circle
              cx={size / 2}
              cy={size / 2}
              r={r}
              fill="none"
              stroke={trackColor}
              strokeWidth={stroke}
              strokeLinecap="round"
              strokeDasharray={c}
              strokeDashoffset={offset}
              transform={`rotate(-90 ${size / 2} ${size / 2})`}
            />
            <text
              x="50%"
              y="50%"
              dominantBaseline="central"
              textAnchor="middle"
              fontSize={Math.max(8, Math.round(size * 0.32))}
              fill="rgba(0,0,0,0.65)"
            >
              {Math.round(pct)}
            </text>
          </svg>
        </div>
      );
    }

    const bar = (
      <div
        style={{
          flex: 1,
          height: 8,
          borderRadius: 99,
          background: "rgba(0,0,0,0.08)",
          overflow: "hidden",
          minWidth: 24,
        }}
      >
        <div style={{ width: `${pct}%`, height: "100%", background: trackColor }} />
      </div>
    );

    return (
      <div style={{ ...common, gap: 8 }}>
        {bar}
        {display === "barLabel" ? label : null}
      </div>
    );
  }

  if (cell.widget === "image") {
    const w = cell.widgetProps?.imageWidth ?? 28;
    const h = cell.widgetProps?.imageHeight ?? 28;
    return (
      <div style={common}>
        {cell.imageUrl ? (
          <img
            src={cell.imageUrl}
            alt=""
            style={{
              width: w,
              height: h,
              objectFit: cell.widgetProps?.imageObjectFit ?? "cover",
              borderRadius: 4,
            }}
            draggable={false}
          />
        ) : (
          <span style={{ fontSize: 11, opacity: 0.5 }}>—</span>
        )}
      </div>
    );
  }

  if (cell.widget === "boolean") {
    const on = Boolean(cell.booleanValue);
    const canToggle = Boolean(interactive && onCellAction);
    return (
      <div style={common}>
        <button
          type="button"
          disabled={!canToggle}
          onMouseDown={(e) => e.stopPropagation()}
          onClick={(e) => {
            e.stopPropagation();
            if (!canToggle) return;
            if (on) {
              emit("toggleOff", cell.widgetProps?.actions?.onFalseBlueprintNodeId);
            } else {
              emit("toggleOn", cell.widgetProps?.actions?.onTrueBlueprintNodeId);
            }
          }}
          style={{
            width: 28,
            height: 16,
            borderRadius: 99,
            background: on ? "#16a34a" : "rgba(0,0,0,0.2)",
            position: "relative",
            display: "inline-block",
            flex: "0 0 auto",
            border: "none",
            padding: 0,
            cursor: canToggle ? "pointer" : "default",
          }}
          aria-pressed={on}
        >
          <span
            style={{
              position: "absolute",
              top: 2,
              left: on ? 14 : 2,
              width: 12,
              height: 12,
              borderRadius: 99,
              background: "#fff",
            }}
          />
        </button>
        <span style={{ marginLeft: 6, fontSize: 12 }}>{cell.text}</span>
      </div>
    );
  }

  const textStyle = cell.widgetProps?.textStyle;
  const canClickText = Boolean(cell.widgetProps?.actions?.onClickBlueprintNodeId);
  return (
    <div
      style={{
        ...common,
        fontFamily: textStyle?.fontFamily,
        fontStyle: textStyle?.fontStyle,
        textDecoration: textStyle?.textDecoration === "none" ? undefined : textStyle?.textDecoration,
        cursor: canClickText ? "pointer" : undefined,
        color: canClickText && !common.color ? "#2563eb" : common.color,
      }}
      title={cell.text}
      onClick={(e) => {
        if (!canClickText) return;
        e.stopPropagation();
        emit("click", cell.widgetProps?.actions?.onClickBlueprintNodeId);
      }}
    >
      {cell.text}
    </div>
  );
}

const MemoCell = React.memo(TableCellView);

function TableRow({
  row,
  columns,
  config,
  rowHeight,
  gridTemplate,
  elementId,
  interactive,
  onCellAction,
}: {
  row: NormalizedRow;
  columns: NormalizedColumn[];
  config: PanelTableConfig;
  rowHeight: number;
  gridTemplate: string;
  elementId: string;
  interactive?: boolean;
  onCellAction?: TableCellActionHandler;
}) {
  const rowDisplay = resolveRowDisplay(row, config);
  return (
    <div
      role="row"
      style={{
        display: "grid",
        gridTemplateColumns: gridTemplate,
        height: rowHeight,
        boxSizing: "border-box",
        borderBottom: "1px solid rgba(0,0,0,0.06)",
        ...stylePropsToCss(rowDisplay.style),
      }}
    >
      {columns.map((col) => {
        const cell = resolveCellDisplay(row, col, config);
        return (
          <div
            key={col.id}
            role="cell"
            style={{
              minWidth: 0,
              borderRight: "1px solid rgba(0,0,0,0.04)",
            }}
          >
            <MemoCell
              cell={cell}
              row={row}
              column={col}
              elementId={elementId}
              interactive={interactive}
              onCellAction={onCellAction}
            />
          </div>
        );
      })}
    </div>
  );
}

const MemoRow = React.memo(TableRow);

export function TableNodeContent({
  element,
  interactive = true,
  onCellAction,
}: {
  element: PanelElement;
  interactive?: boolean;
  onCellAction?: TableCellActionHandler;
}) {
  const { t } = useI18n();
  const parentRef = useRef<HTMLDivElement | null>(null);
  const config = element.table;

  const model = useMemo(() => {
    const cfg = config ?? {};
    const raw = resolveRawTableInput(cfg);
    return transformToTableCached(raw, cfg);
  }, [config]);

  const columns = model.columns;
  const tableConfig = config ?? {};
  const rowHeight = Math.max(24, tableConfig.rowHeight ?? 36);
  const showHeader = tableConfig.showHeader !== false;
  const emptyText = tableConfig.emptyText || t("panel.config.tableEmpty");

  const gridTemplate = useMemo(
    () =>
      columns
        .map((c) => {
          if (c.width) return `${c.width}px`;
          if (c.minWidth) return `minmax(${c.minWidth}px, 1fr)`;
          return "minmax(96px, 1fr)";
        })
        .join(" "),
    [columns]
  );

  const virtualizer = useVirtualizer({
    count: model.rows.length,
    getScrollElement: () => parentRef.current,
    estimateSize: () => rowHeight,
    overscan: 8,
  });

  const tableStyle = stylePropsToCss(tableConfig.tableStyle ?? {});
  const headerStyle = stylePropsToCss(tableConfig.headerStyle ?? {});
  const tableTextColor =
    (typeof tableStyle.color === "string" && tableStyle.color.trim()) ||
    (typeof tableConfig.tableStyle?.color === "string" && tableConfig.tableStyle.color.trim()) ||
    "#111827";
  const headerTextColor =
    (typeof headerStyle.color === "string" && headerStyle.color.trim()) ||
    (typeof tableConfig.headerStyle?.color === "string" && tableConfig.headerStyle.color.trim()) ||
    tableTextColor;

  return (
    <div
      className="rv-table-node h-full w-full overflow-hidden"
      style={{
        background: (tableConfig.tableStyle?.backgroundColor as string) || "#fff",
        border:
          tableConfig.tableStyle?.borderWidth != null
            ? `${tableConfig.tableStyle.borderWidth}px solid ${tableConfig.tableStyle.borderColor ?? "rgba(0,0,0,0.12)"}`
            : "1px solid rgba(0,0,0,0.08)",
        borderRadius: tableConfig.tableStyle?.borderRadius ?? 6,
        fontSize: tableConfig.tableStyle?.fontSize ?? 12,
        ...tableStyle,
        color: tableTextColor,
        display: "flex",
        flexDirection: "column",
      }}
    >
      {showHeader ? (
        <div
          role="row"
          style={{
            display: "grid",
            gridTemplateColumns: gridTemplate,
            height: rowHeight,
            flex: "0 0 auto",
            position: tableConfig.tableStyle?.stickyHeader === false ? "relative" : "sticky",
            top: 0,
            zIndex: 2,
            background: (tableConfig.headerStyle?.backgroundColor as string) || "rgba(0,0,0,0.04)",
            borderBottom: "1px solid rgba(0,0,0,0.1)",
            ...headerStyle,
            color: headerTextColor,
          }}
        >
          {columns.map((col) => {
            const headerLabel = (col.title ?? "").trim() || col.field || col.id;
            return (
              <div
                key={col.id}
                role="columnheader"
                style={{
                  padding: "0 8px",
                  display: "flex",
                  alignItems: "center",
                  fontWeight: tableConfig.headerStyle?.fontWeight ?? 600,
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                  whiteSpace: "nowrap",
                  borderRight: "1px solid rgba(0,0,0,0.04)",
                  textAlign: col.align,
                  justifyContent:
                    col.align === "center" ? "center" : col.align === "right" ? "flex-end" : "flex-start",
                }}
                title={headerLabel}
              >
                {headerLabel}
              </div>
            );
          })}
        </div>
      ) : null}

      <div ref={parentRef} className="min-h-0 flex-1 overflow-auto">
        {model.rows.length === 0 ? (
          <div className="flex h-full flex-col items-center justify-center gap-2 px-3 text-center text-xs text-muted-foreground">
            <svg
              viewBox="0 0 48 48"
              className="h-10 w-10 opacity-45"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.6"
              aria-hidden
            >
              <rect x="8" y="12" width="32" height="24" rx="3" />
              <path d="M8 20h32M20 12v24M28 12v24" strokeOpacity="0.55" />
              <circle cx="24" cy="30" r="1.2" fill="currentColor" stroke="none" />
            </svg>
            <div>{emptyText}</div>
          </div>
        ) : (
          <div style={{ height: virtualizer.getTotalSize(), position: "relative", width: "100%" }}>
            {virtualizer.getVirtualItems().map((item) => {
              const row = model.rows[item.index];
              return (
                <div
                  key={row.id}
                  style={{
                    position: "absolute",
                    top: 0,
                    left: 0,
                    width: "100%",
                    height: item.size,
                    transform: `translateY(${item.start}px)`,
                  }}
                >
                  <MemoRow
                    row={row}
                    columns={columns}
                    config={tableConfig}
                    rowHeight={rowHeight}
                    gridTemplate={gridTemplate}
                    elementId={element.id}
                    interactive={interactive}
                    onCellAction={onCellAction}
                  />
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
