// packages/vue-blueprint/src/components/BlueprintNodeSwitchTaskDialog.vue
<script setup lang="ts">
import { useI18n } from "@arronqzy/i18n/vue";
import { computed } from "vue";
import { Button, Modal } from "ant-design-vue";

const { t } = useI18n();
export type BlueprintNodeSwitchTaskDialogProps = {
  open: boolean;
  fromNodeId: string;
  toNodeId: string | null;
  onOpenChange: (open: boolean) => void;
  onKeepTaskAndSwitch: () => void;
  onCancelTaskAndSwitch: () => void;
};

const props = defineProps<BlueprintNodeSwitchTaskDialogProps>();

const targetLabel = computed(() =>
  props.toNodeId === null
    ? t("blueprint.dialog.cancelSelection")
    : t("blueprint.dialog.nodeTarget", { id: props.toNodeId })
);
</script>

<template>
  <Modal
    :open="open"
    :title="t('blueprint.dialog.taskRunningTitle')"
    :footer="null"
    @update:open="onOpenChange"
  >
    <p class="text-sm text-muted-foreground">
      {{
        t("blueprint.dialog.taskRunningDescription", {
          fromNodeId,
          target: targetLabel,
        })
      }}
    </p>
    <p class="mt-2 text-xs text-muted-foreground">
      {{ t("blueprint.dialog.taskSwitchHint") }}
    </p>
    <div class="mt-4 flex flex-wrap justify-end gap-2">
      <Button @click="onOpenChange(false)">{{ t("blueprint.dialog.stayOnNode") }}</Button>
      <Button @click="onCancelTaskAndSwitch">{{ t("blueprint.dialog.cancelAndSwitch") }}</Button>
      <Button type="primary" @click="onKeepTaskAndSwitch">{{ t("blueprint.dialog.keepAndSwitch") }}</Button>
    </div>
  </Modal>
</template>

// packages/react-blueprint/src/components/BlueprintNodeSwitchTaskDialog.tsx
import {
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@arronqzy/ui";
import { useI18n } from "@arronqzy/i18n/react";

export type BlueprintNodeSwitchTaskDialogProps = {
  open: boolean;
  fromNodeId: string;
  toNodeId: string | null;
  onOpenChange: (open: boolean) => void;
  onKeepTaskAndSwitch: () => void;
  onCancelTaskAndSwitch: () => void;
};

export function BlueprintNodeSwitchTaskDialog({
  open,
  fromNodeId,
  toNodeId,
  onOpenChange,
  onKeepTaskAndSwitch,
  onCancelTaskAndSwitch,
}: BlueprintNodeSwitchTaskDialogProps) {
  const { t } = useI18n();
  const targetLabel =
    toNodeId === null
      ? t("blueprint.dialog.cancelSelection")
      : t("blueprint.dialog.nodeTarget", { id: toNodeId });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{t("blueprint.dialog.taskRunningTitle")}</DialogTitle>
          <DialogDescription>
            {t("blueprint.dialog.taskRunningDescription", {
              fromNodeId,
              target: targetLabel,
            })}
          </DialogDescription>
        </DialogHeader>
        <p className="text-xs text-muted-foreground">
          {t("blueprint.dialog.taskSwitchHint")}
        </p>
        <DialogFooter className="gap-2 sm:gap-0">
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            {t("blueprint.dialog.stayOnNode")}
          </Button>
          <Button type="button" variant="secondary" onClick={onCancelTaskAndSwitch}>
            {t("blueprint.dialog.cancelAndSwitch")}
          </Button>
          <Button type="button" onClick={onKeepTaskAndSwitch}>
            {t("blueprint.dialog.keepAndSwitch")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
