// packages/vue-blueprint/src/components/FetchNodeConfigPanel.vue
<script setup lang="ts">
import { useI18n } from "@arronqzy/i18n/vue";
import { computed, ref } from "vue";
import { Button, Input, Select } from "ant-design-vue";
import type {
  FetchHttpMethod,
  FetchRequestConfig,
  FetchResponseType,
} from "@arronqzy/blueprint-dsl";
import {
  FETCH_CACHES,
  FETCH_CREDENTIALS,
  FETCH_HTTP_METHODS,
  FETCH_MODES,
  FETCH_NODE_TYPE,
  FETCH_REDIRECTS,
  FETCH_RESPONSE_TYPES,
} from "@arronqzy/blueprint-dsl";

import type { BlueprintGraphNode } from "../graph/document";
import { resolveNodeFetchConfig } from "../graph/document";
import {
  cancelFetchDebugTask,
  cancelSwaggerLoadTask,
  startFetchDebugTask,
  startSwaggerLoadTask,
  useFetchDebugTask,
  useSwaggerLoadTask,
} from "../fetch-config-task-store";
import FetchUrlAutocomplete from "./FetchUrlAutocomplete.vue";

const { t } = useI18n();

export type FetchNodeConfigPanelProps = {
  node: BlueprintGraphNode;
  onUpdateNode: (
    nodeId: string,
    patch: Partial<Pick<BlueprintGraphNode, "fetchConfig" | "configSource">>
  ) => void;
};

const props = defineProps<FetchNodeConfigPanelProps>();

const validationError = ref<string | null>(null);
const fetchValidationError = ref<string | null>(null);
const debugExpanded = ref(false);

const fetchConfig = computed(() => resolveNodeFetchConfig(props.node));
const endpoints = computed(() => fetchConfig.value.swaggerEndpoints ?? []);
const hasSwaggerEndpoints = computed(() => endpoints.value.length > 0);
const urlInputMode = computed(
  () => fetchConfig.value.urlInputMode ?? (hasSwaggerEndpoints.value ? "swagger" : "manual")
);

const swaggerTask = useSwaggerLoadTask(props.node.id);
const fetchDebugTask = useFetchDebugTask(props.node.id);
const loadingSwagger = computed(() => swaggerTask.value.status === "loading");
const loadingFetchDebug = computed(() => fetchDebugTask.value.status === "loading");
const swaggerTaskError = computed(() =>
  swaggerTask.value.status === "error" ? swaggerTask.value.error : null
);
const swaggerError = computed(() => validationError.value ?? swaggerTaskError.value);

function patchFetchConfig(node: BlueprintGraphNode, patch: Partial<FetchRequestConfig>) {
  return {
    role: "fetch" as const,
    nodeType: FETCH_NODE_TYPE,
    configSource: "fetch" as const,
    fetchConfig: { ...resolveNodeFetchConfig(node), ...patch },
  };
}

function setUrlInputMode(mode: "swagger" | "manual") {
  props.onUpdateNode(props.node.id, patchFetchConfig(props.node, { urlInputMode: mode }));
}

function handleLoadSwagger() {
  const docsUrl = fetchConfig.value.swaggerDocsUrl?.trim();
  if (!docsUrl) {
    validationError.value = t("blueprint.config.fillSwaggerUrlFirst");
    return;
  }

  validationError.value = null;
  startSwaggerLoadTask({
    nodeId: props.node.id,
    docsUrl,
    onSuccess: (parsed, url) => {
      props.onUpdateNode(
        props.node.id,
        patchFetchConfig(props.node, {
          swaggerDocsUrl: url,
          apiBaseUrl: parsed.apiBaseUrl,
          swaggerEndpoints: parsed.endpoints,
          urlInputMode: "swagger",
        })
      );
    },
  });
}

function handleAbortSwagger() {
  cancelSwaggerLoadTask(props.node.id);
  validationError.value = null;
}

function handleSendFetchDebug() {
  const url = fetchConfig.value.url?.trim();
  if (!url) {
    fetchValidationError.value = t("blueprint.config.fillRequestUrlFirst");
    return;
  }

  fetchValidationError.value = null;
  startFetchDebugTask({
    nodeId: props.node.id,
    config: fetchConfig.value,
  });
}

function handleAbortFetchDebug() {
  cancelFetchDebugTask(props.node.id);
  fetchValidationError.value = null;
}

function formatFetchDebugData(data: unknown): string {
  if (typeof data === "string") return data;
  try {
    return JSON.stringify(data, null, 2);
  } catch {
    return String(data);
  }
}

const debugBodyText = computed(() => {
  const task = fetchDebugTask.value;
  if (task.status !== "success" || !task.result) return "";
  return formatFetchDebugData(task.result.data);
});

const debugPreview = computed(() => {
  const text = debugBodyText.value;
  return text.length > 120 ? `${text.slice(0, 120).trimEnd()}…` : text;
});

const debugOk = computed(() => {
  const result = fetchDebugTask.value.result;
  return result ? result.status >= 200 && result.status < 300 : false;
});

function handleHeadersBlur(event: Event) {
  try {
    const headers = JSON.parse((event.target as HTMLTextAreaElement).value || "{}") as Record<
      string,
      string
    >;
    props.onUpdateNode(props.node.id, patchFetchConfig(props.node, { headers }));
  } catch {
    /* 保留上次有效值 */
  }
}
</script>

<template>
  <div class="space-y-2 rounded-md border border-border/70 bg-muted/20 p-2.5">
    <div class="font-medium text-foreground">{{ t("blueprint.config.fetchTitle") }}</div>
    <p class="text-[11px] text-muted-foreground">
      {{ t("blueprint.config.fetchHint") }}
    </p>

    <label class="block space-y-1">
      <span class="text-muted-foreground">{{ t("blueprint.config.swaggerUrlOptional") }}</span>
      <div class="flex gap-1.5">
        <Input
          size="small"
          :value="fetchConfig.swaggerDocsUrl ?? ''"
          :disabled="loadingSwagger"
          placeholder="https://example.com/v3/api-docs"
          class="flex-1 font-mono text-[11px]"
          @update:value="
            (v) =>
              onUpdateNode(node.id, patchFetchConfig(node, { swaggerDocsUrl: String(v) }))
          "
        />
        <Button
          v-if="loadingSwagger"
          size="small"
          class="h-8 w-8 shrink-0 text-destructive"
          :title="t('blueprint.config.abortParse')"
          :aria-label="t('blueprint.config.abortSwaggerAria')"
          @click="handleAbortSwagger"
        >
          ■
        </Button>
        <Button
          v-else
          size="small"
          class="h-8 w-8 shrink-0"
          :title="t('blueprint.config.parseSwagger')"
          @click="handleLoadSwagger"
        >
          ➤
        </Button>
      </div>
      <p v-if="loadingSwagger" class="text-[11px] text-muted-foreground">
        {{ t("blueprint.config.parsingSwagger") }}
      </p>
      <p v-if="swaggerError" class="text-[11px] text-destructive">{{ swaggerError }}</p>
      <p v-if="endpoints.length > 0" class="text-[11px] text-muted-foreground">
        {{ t("blueprint.config.parsedEndpoints", { count: endpoints.length }) }}
      </p>
    </label>

    <label class="block space-y-1">
      <div class="flex items-center justify-between gap-2">
        <span class="text-muted-foreground">{{ t("blueprint.config.requestUrl") }}</span>
        <div v-if="hasSwaggerEndpoints" class="flex rounded-md border border-border p-0.5">
          <button
            type="button"
            :disabled="loadingSwagger"
            class="rounded px-2 py-0.5 text-[10px] transition-colors disabled:cursor-not-allowed disabled:opacity-50"
            :class="
              urlInputMode === 'swagger'
                ? 'bg-primary text-primary-foreground'
                : 'text-muted-foreground hover:text-foreground'
            "
            @click="setUrlInputMode('swagger')"
          >
            {{ t("blueprint.config.suggestApi") }}
          </button>
          <button
            type="button"
            :disabled="loadingSwagger"
            class="rounded px-2 py-0.5 text-[10px] transition-colors disabled:cursor-not-allowed disabled:opacity-50"
            :class="
              urlInputMode === 'manual'
                ? 'bg-primary text-primary-foreground'
                : 'text-muted-foreground hover:text-foreground'
            "
            @click="setUrlInputMode('manual')"
          >
            {{ t("blueprint.config.manualInput") }}
          </button>
        </div>
      </div>

      <div
        v-if="urlInputMode === 'swagger' && hasSwaggerEndpoints"
        class="space-y-2"
        :class="loadingSwagger && 'pointer-events-none opacity-60'"
      >
        <label class="block space-y-1">
          <span class="text-muted-foreground">{{ t("blueprint.config.apiHostBaseUrl") }}</span>
          <Input
            size="small"
            :value="fetchConfig.apiBaseUrl ?? ''"
            placeholder="https://api.example.com/v1"
            class="font-mono text-[11px]"
            @update:value="
              (v) => onUpdateNode(node.id, patchFetchConfig(node, { apiBaseUrl: String(v) }))
            "
          />
        </label>
        <label class="block space-y-1">
          <span class="text-muted-foreground">{{ t("blueprint.config.selectEndpoint") }}</span>
          <div class="flex gap-1.5">
            <div class="min-w-0 flex-1">
              <FetchUrlAutocomplete
                :value="fetchConfig.url"
                :api-base-url="fetchConfig.apiBaseUrl ?? ''"
                :endpoints="endpoints"
                select-only
                :placeholder="t('blueprint.config.selectOrSearchEndpoint')"
                @change="
                  (url) => onUpdateNode(node.id, patchFetchConfig(node, { url }))
                "
                @select-endpoint="
                  (endpoint) =>
                    onUpdateNode(
                      node.id,
                      patchFetchConfig(node, {
                        url: endpoint.path,
                        method: endpoint.method,
                      })
                    )
                "
              />
            </div>
            <Button
              v-if="loadingFetchDebug"
              size="small"
              class="h-8 w-8 shrink-0"
              :title="t('blueprint.config.abortRequest')"
              @click="handleAbortFetchDebug"
            >
              ■
            </Button>
            <Button
              v-else
              size="small"
              class="h-8 w-8 shrink-0"
              :disabled="loadingSwagger"
              :title="t('blueprint.config.sendDebugRequest')"
              @click="handleSendFetchDebug"
            >
              ➤
            </Button>
          </div>
        </label>
      </div>
      <div v-else class="flex gap-1.5">
        <Input
          size="small"
          :value="fetchConfig.url"
          :disabled="loadingFetchDebug"
          placeholder="https://api.example.com/data"
          class="flex-1 font-mono text-[11px]"
          @update:value="(v) => onUpdateNode(node.id, patchFetchConfig(node, { url: String(v) }))"
        />
        <Button
          v-if="loadingFetchDebug"
          size="small"
          class="h-8 w-8 shrink-0"
          :title="t('blueprint.config.abortRequest')"
          @click="handleAbortFetchDebug"
        >
          ■
        </Button>
        <Button
          v-else
          size="small"
          class="h-8 w-8 shrink-0"
          :disabled="loadingSwagger"
          :title="t('blueprint.config.sendDebugRequest')"
          @click="handleSendFetchDebug"
        >
          ➤
        </Button>
      </div>

      <p v-if="loadingFetchDebug" class="text-[11px] text-muted-foreground">
        {{ t("blueprint.config.sendingDebug") }}
      </p>
      <p v-if="fetchValidationError" class="text-[11px] text-destructive">
        {{ fetchValidationError }}
      </p>

      <div
        v-if="fetchDebugTask.status === 'error'"
        class="rounded-md border border-destructive/40 bg-destructive/5 p-2"
      >
        <p class="text-[11px] text-destructive">
          {{ fetchDebugTask.error ?? t("blueprint.config.requestFailed") }}
        </p>
      </div>
      <div
        v-else-if="fetchDebugTask.status === 'success' && fetchDebugTask.result"
        class="rounded-md border border-border/70 bg-background/80"
      >
        <button
          type="button"
          class="flex w-full items-center gap-2 px-2 py-1.5 text-left"
          @click="debugExpanded = !debugExpanded"
        >
          <span
            class="text-muted-foreground transition-transform"
            :class="debugExpanded && 'rotate-180'"
          >
            ▼
          </span>
          <span class="text-[11px] font-medium text-foreground">{{ t("blueprint.config.debugResponse") }}</span>
          <span
            class="rounded px-1.5 py-0.5 font-mono text-[10px]"
            :class="
              debugOk
                ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300'
                : 'bg-destructive/15 text-destructive'
            "
          >
            {{ fetchDebugTask.result.status }} {{ fetchDebugTask.result.statusText }}
          </span>
          <span
            v-if="!debugExpanded"
            class="min-w-0 flex-1 truncate font-mono text-[10px] text-muted-foreground"
          >
            {{ debugPreview }}
          </span>
        </button>
        <div v-if="debugExpanded" class="border-t border-border/60 px-2 py-2">
          <div class="mb-1 truncate font-mono text-[10px] text-muted-foreground">
            {{ fetchDebugTask.result.url }}
          </div>
          <pre
            class="max-h-56 overflow-auto whitespace-pre-wrap break-all rounded bg-muted/30 p-2 font-mono text-[10px] leading-relaxed text-foreground"
          >{{ debugBodyText }}</pre>
        </div>
      </div>
    </label>

    <label class="block space-y-1">
      <span class="text-muted-foreground">{{ t("blueprint.config.requestMethod") }}</span>
      <Select
        size="small"
        class="w-full"
        :value="fetchConfig.method ?? 'GET'"
        @change="
          (v) =>
            onUpdateNode(
              node.id,
              patchFetchConfig(node, { method: v as FetchHttpMethod })
            )
        "
      >
        <Select.Option v-for="method in FETCH_HTTP_METHODS" :key="method" :value="method">
          {{ method }}
        </Select.Option>
      </Select>
    </label>

    <label class="block space-y-1">
      <span class="text-muted-foreground">{{ t("blueprint.config.requestHeadersJson") }}</span>
      <textarea
        :key="`${node.id}-headers-${JSON.stringify(fetchConfig.headers)}`"
        :value="JSON.stringify(fetchConfig.headers ?? {}, null, 2)"
        rows="4"
        class="w-full rounded-md border border-input bg-background px-2 py-1.5 font-mono text-[11px] leading-relaxed text-foreground shadow-sm outline-none focus-visible:ring-1 focus-visible:ring-primary"
        placeholder='{"Content-Type":"application/json"}'
        @blur="handleHeadersBlur"
      />
    </label>

    <label class="block space-y-1">
      <span class="text-muted-foreground">{{ t("blueprint.config.requestBody") }}</span>
      <textarea
        :value="fetchConfig.body ?? ''"
        rows="4"
        class="w-full rounded-md border border-input bg-background px-2 py-1.5 font-mono text-[11px] leading-relaxed text-foreground shadow-sm outline-none focus-visible:ring-1 focus-visible:ring-primary"
        placeholder='{"key":"value"}'
        @input="
          (e) =>
            onUpdateNode(
              node.id,
              patchFetchConfig(node, { body: (e.target as HTMLTextAreaElement).value })
            )
        "
      />
    </label>

    <div class="grid grid-cols-2 gap-2">
      <label class="block space-y-1">
        <span class="text-muted-foreground">Credentials</span>
        <Select
          size="small"
          class="w-full"
          :value="fetchConfig.credentials ?? 'same-origin'"
          @change="
            (v) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { credentials: v as RequestCredentials })
              )
          "
        >
          <Select.Option v-for="item in FETCH_CREDENTIALS" :key="item" :value="item">
            {{ item }}
          </Select.Option>
        </Select>
      </label>
      <label class="block space-y-1">
        <span class="text-muted-foreground">Mode</span>
        <Select
          size="small"
          class="w-full"
          :value="fetchConfig.mode ?? 'cors'"
          @change="
            (v) =>
              onUpdateNode(node.id, patchFetchConfig(node, { mode: v as RequestMode }))
          "
        >
          <Select.Option v-for="item in FETCH_MODES" :key="item" :value="item">
            {{ item }}
          </Select.Option>
        </Select>
      </label>
      <label class="block space-y-1">
        <span class="text-muted-foreground">Cache</span>
        <Select
          size="small"
          class="w-full"
          :value="fetchConfig.cache ?? 'default'"
          @change="
            (v) =>
              onUpdateNode(node.id, patchFetchConfig(node, { cache: v as RequestCache }))
          "
        >
          <Select.Option v-for="item in FETCH_CACHES" :key="item" :value="item">
            {{ item }}
          </Select.Option>
        </Select>
      </label>
      <label class="block space-y-1">
        <span class="text-muted-foreground">Redirect</span>
        <Select
          size="small"
          class="w-full"
          :value="fetchConfig.redirect ?? 'follow'"
          @change="
            (v) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { redirect: v as RequestRedirect })
              )
          "
        >
          <Select.Option v-for="item in FETCH_REDIRECTS" :key="item" :value="item">
            {{ item }}
          </Select.Option>
        </Select>
      </label>
    </div>

    <div class="grid grid-cols-2 gap-2">
      <label class="block space-y-1">
        <span class="text-muted-foreground">{{ t("blueprint.config.responseParse") }}</span>
        <Select
          size="small"
          class="w-full"
          :value="fetchConfig.responseType ?? 'json'"
          @change="
            (v) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { responseType: v as FetchResponseType })
              )
          "
        >
          <Select.Option v-for="item in FETCH_RESPONSE_TYPES" :key="item" :value="item">
            {{ item }}
          </Select.Option>
        </Select>
      </label>
      <label class="block space-y-1">
        <span class="text-muted-foreground">{{ t("blueprint.config.timeoutMs") }}</span>
        <Input
          type="number"
          size="small"
          :min="0"
          :step="1000"
          :value="fetchConfig.timeoutMs ?? 30000"
          @update:value="
            (v) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { timeoutMs: Number(v) || 0 })
              )
          "
        />
      </label>
    </div>
  </div>
</template>

// packages/react-blueprint/src/components/FetchNodeConfigPanel.tsx
import { useCallback, useState, type ChangeEvent } from "react";
import {
  Button,
  Input,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
  cn,
} from "@arronqzy/ui";
import type {
  FetchHttpMethod,
  FetchRequestConfig,
  FetchResponseType,
} from "@arronqzy/blueprint-dsl";
import {
  FETCH_CACHES,
  FETCH_CREDENTIALS,
  FETCH_HTTP_METHODS,
  FETCH_MODES,
  FETCH_NODE_TYPE,
  FETCH_REDIRECTS,
  FETCH_RESPONSE_TYPES,
} from "@arronqzy/blueprint-dsl";

import type { BlueprintGraphNode } from "../graph/document";
import { resolveNodeFetchConfig } from "../graph/document";
import {
  cancelSwaggerLoadTask,
  cancelFetchDebugTask,
  startFetchDebugTask,
  startSwaggerLoadTask,
  useFetchDebugTask,
  useSwaggerLoadTask,
} from "../fetch-config-task-store";
import { useI18n } from "@arronqzy/i18n/react";

import { FetchUrlAutocomplete } from "./FetchUrlAutocomplete";

function SendIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className={className}
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <path d="M22 2 11 13" />
      <path d="M22 2 15 22l-4-9-9-4z" />
    </svg>
  );
}

function StopIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className={className}
      fill="currentColor"
      aria-hidden="true"
    >
      <rect x="6" y="6" width="12" height="12" rx="1" />
    </svg>
  );
}

function ChevronIcon({ className, expanded }: { className?: string; expanded: boolean }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className={cn("transition-transform", expanded && "rotate-180", className)}
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

function AsyncSendButton({
  loading,
  disabled,
  onSend,
  onAbort,
  sendTitle,
  abortTitle,
  sendAriaLabel,
  abortAriaLabel,
}: {
  loading: boolean;
  disabled?: boolean;
  onSend: () => void;
  onAbort: () => void;
  sendTitle: string;
  abortTitle: string;
  sendAriaLabel: string;
  abortAriaLabel: string;
}) {
  if (loading) {
    return (
      <Button
        type="button"
        variant="outline"
        size="icon"
        className="h-8 w-8 shrink-0 text-destructive hover:bg-destructive/10 hover:text-destructive"
        title={abortTitle}
        aria-label={abortAriaLabel}
        onClick={onAbort}
      >
        <StopIcon className="h-3.5 w-3.5" />
      </Button>
    );
  }

  return (
    <Button
      type="button"
      variant="outline"
      size="icon"
      className="h-8 w-8 shrink-0"
      title={sendTitle}
      aria-label={sendAriaLabel}
      disabled={disabled}
      onClick={onSend}
    >
      <SendIcon className="h-4 w-4" />
    </Button>
  );
}

function formatFetchDebugData(data: unknown): string {
  if (typeof data === "string") return data;
  try {
    return JSON.stringify(data, null, 2);
  } catch {
    return String(data);
  }
}

function FetchDebugResponsePanel({
  task,
}: {
  task: ReturnType<typeof useFetchDebugTask>;
}) {
  const { t } = useI18n();
  const [expanded, setExpanded] = useState(false);

  if (task.status === "idle" || task.status === "loading") return null;

  if (task.status === "error") {
    return (
      <div className="rounded-md border border-destructive/40 bg-destructive/5 p-2">
        <p className="text-[11px] text-destructive">{task.error ?? t("blueprint.config.requestFailed")}</p>
      </div>
    );
  }

  const result = task.result;
  if (!result) return null;

  const bodyText = formatFetchDebugData(result.data);
  const preview =
    bodyText.length > 120 ? `${bodyText.slice(0, 120).trimEnd()}…` : bodyText;
  const ok = result.status >= 200 && result.status < 300;

  return (
    <div className="rounded-md border border-border/70 bg-background/80">
      <button
        type="button"
        className="flex w-full items-center gap-2 px-2 py-1.5 text-left"
        onClick={() => setExpanded((value) => !value)}
      >
        <ChevronIcon className="h-3.5 w-3.5 shrink-0 text-muted-foreground" expanded={expanded} />
        <span className="text-[11px] font-medium text-foreground">{t("blueprint.config.debugResponse")}</span>
        <span
          className={cn(
            "rounded px-1.5 py-0.5 font-mono text-[10px]",
            ok
              ? "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300"
              : "bg-destructive/15 text-destructive"
          )}
        >
          {result.status} {result.statusText}
        </span>
        {!expanded ? (
          <span className="min-w-0 flex-1 truncate font-mono text-[10px] text-muted-foreground">
            {preview}
          </span>
        ) : null}
      </button>
      {expanded ? (
        <div className="border-t border-border/60 px-2 py-2">
          <div className="mb-1 truncate font-mono text-[10px] text-muted-foreground">
            {result.url}
          </div>
          <pre className="max-h-56 overflow-auto whitespace-pre-wrap break-all rounded bg-muted/30 p-2 font-mono text-[10px] leading-relaxed text-foreground">
            {bodyText}
          </pre>
        </div>
      ) : null}
    </div>
  );
}

function LoaderIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      className={cn("animate-spin", className)}
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      aria-hidden="true"
    >
      <path d="M12 2v4" />
      <path d="m16.2 7.8 2.9-2.9" />
      <path d="M18 12h4" />
      <path d="m16.2 16.2 2.9 2.9" />
      <path d="M12 18v4" />
      <path d="m4.9 19.1 2.9-2.9" />
      <path d="M2 12h4" />
      <path d="m4.9 4.9 2.9 2.9" />
    </svg>
  );
}

export type FetchNodeConfigPanelProps = {
  node: BlueprintGraphNode;
  onUpdateNode: (
    nodeId: string,
    patch: Partial<Pick<BlueprintGraphNode, "fetchConfig" | "configSource">>
  ) => void;
};

function patchFetchConfig(
  node: BlueprintGraphNode,
  patch: Partial<FetchRequestConfig>
) {
  return {
    role: "fetch" as const,
    nodeType: FETCH_NODE_TYPE,
    configSource: "fetch" as const,
    fetchConfig: { ...resolveNodeFetchConfig(node), ...patch },
  };
}

export function FetchNodeConfigPanel({
  node,
  onUpdateNode,
}: FetchNodeConfigPanelProps) {
  const { t } = useI18n();
  const fetchConfig = resolveNodeFetchConfig(node);
  const endpoints = fetchConfig.swaggerEndpoints ?? [];
  const hasSwaggerEndpoints = endpoints.length > 0;
  const urlInputMode =
    fetchConfig.urlInputMode ?? (hasSwaggerEndpoints ? "swagger" : "manual");
  const swaggerTask = useSwaggerLoadTask(node.id);
  const fetchDebugTask = useFetchDebugTask(node.id);
  const loadingSwagger = swaggerTask.status === "loading";
  const loadingFetchDebug = fetchDebugTask.status === "loading";
  const swaggerTaskError =
    swaggerTask.status === "error" ? swaggerTask.error : null;
  const [validationError, setValidationError] = useState<string | null>(null);
  const [fetchValidationError, setFetchValidationError] = useState<string | null>(null);
  const swaggerError = validationError ?? swaggerTaskError;

  const setUrlInputMode = useCallback(
    (mode: "swagger" | "manual") => {
      onUpdateNode(node.id, patchFetchConfig(node, { urlInputMode: mode }));
    },
    [node, onUpdateNode]
  );

  const handleLoadSwagger = useCallback(() => {
    const docsUrl = fetchConfig.swaggerDocsUrl?.trim();
    if (!docsUrl) {
      setValidationError(t("blueprint.config.fillSwaggerUrlFirst"));
      return;
    }

    setValidationError(null);
    startSwaggerLoadTask({
      nodeId: node.id,
      docsUrl,
      onSuccess: (parsed, url) => {
        onUpdateNode(
          node.id,
          patchFetchConfig(node, {
            swaggerDocsUrl: url,
            apiBaseUrl: parsed.apiBaseUrl,
            swaggerEndpoints: parsed.endpoints,
            urlInputMode: "swagger",
          })
        );
      },
    });
  }, [fetchConfig.swaggerDocsUrl, node, onUpdateNode]);

  const handleAbortSwagger = useCallback(() => {
    cancelSwaggerLoadTask(node.id);
    setValidationError(null);
  }, [node.id]);

  const handleSendFetchDebug = useCallback(() => {
    const url = fetchConfig.url?.trim();
    if (!url) {
      setFetchValidationError(t("blueprint.config.fillRequestUrlFirst"));
      return;
    }

    setFetchValidationError(null);
    startFetchDebugTask({
      nodeId: node.id,
      config: fetchConfig,
    });
  }, [fetchConfig, node.id]);

  const handleAbortFetchDebug = useCallback(() => {
    cancelFetchDebugTask(node.id);
    setFetchValidationError(null);
  }, [node.id]);

  return (
    <div className="space-y-2 rounded-md border border-border/70 bg-muted/20 p-2.5">
      <div className="font-medium text-foreground">{t("blueprint.config.fetchTitle")}</div>
      <p className="text-[11px] text-muted-foreground">
        {t("blueprint.config.fetchHint")}
      </p>

      <label className="block space-y-1">
        <span className="text-muted-foreground">{t("blueprint.config.swaggerUrlOptional")}</span>
        <div className="flex gap-1.5">
          <Input
            value={fetchConfig.swaggerDocsUrl ?? ""}
            disabled={loadingSwagger}
            onChange={(e: ChangeEvent<HTMLInputElement>) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { swaggerDocsUrl: e.target.value })
              )
            }
            placeholder="https://example.com/v3/api-docs"
            className="h-8 flex-1 font-mono text-[11px]"
          />
          {loadingSwagger ? (
            <Button
              type="button"
              variant="outline"
              size="icon"
              className="h-8 w-8 shrink-0 text-destructive hover:bg-destructive/10 hover:text-destructive"
              title={t("blueprint.config.abortParse")}
              aria-label={t("blueprint.config.abortSwaggerAria")}
              onClick={handleAbortSwagger}
            >
              <StopIcon className="h-3.5 w-3.5" />
            </Button>
          ) : (
            <Button
              type="button"
              variant="outline"
              size="icon"
              className="h-8 w-8 shrink-0"
              title={t("blueprint.config.parseSwagger")}
              onClick={() => handleLoadSwagger()}
            >
              <SendIcon className="h-4 w-4" />
            </Button>
          )}
        </div>
        {loadingSwagger ? (
          <p className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
            <LoaderIcon className="h-3.5 w-3.5 shrink-0" />
            {t("blueprint.config.parsingSwagger")}
          </p>
        ) : null}
        {swaggerError ? (
          <p className="text-[11px] text-destructive">{swaggerError}</p>
        ) : null}
        {endpoints.length > 0 ? (
          <p className="text-[11px] text-muted-foreground">
            {t("blueprint.config.parsedEndpoints", { count: endpoints.length })}
          </p>
        ) : null}
      </label>

      <label className="block space-y-1">
        <div className="flex items-center justify-between gap-2">
          <span className="text-muted-foreground">{t("blueprint.config.requestUrl")}</span>
          {hasSwaggerEndpoints ? (
            <div className="flex rounded-md border border-border p-0.5">
              <button
                type="button"
                disabled={loadingSwagger}
                className={cn(
                  "rounded px-2 py-0.5 text-[10px] transition-colors disabled:cursor-not-allowed disabled:opacity-50",
                  urlInputMode === "swagger"
                    ? "bg-primary text-primary-foreground"
                    : "text-muted-foreground hover:text-foreground"
                )}
                onClick={() => setUrlInputMode("swagger")}
              >
                {t("blueprint.config.suggestApi")}
              </button>
              <button
                type="button"
                disabled={loadingSwagger}
                className={cn(
                  "rounded px-2 py-0.5 text-[10px] transition-colors disabled:cursor-not-allowed disabled:opacity-50",
                  urlInputMode === "manual"
                    ? "bg-primary text-primary-foreground"
                    : "text-muted-foreground hover:text-foreground"
                )}
                onClick={() => setUrlInputMode("manual")}
              >
                {t("blueprint.config.manualInput")}
              </button>
            </div>
          ) : null}
        </div>

        {urlInputMode === "swagger" && hasSwaggerEndpoints ? (
          <div
            className={cn(
              "space-y-2",
              loadingSwagger && "pointer-events-none opacity-60"
            )}
          >
            <label className="block space-y-1">
              <span className="text-muted-foreground">{t("blueprint.config.apiHostBaseUrl")}</span>
              <Input
                value={fetchConfig.apiBaseUrl ?? ""}
                onChange={(e: ChangeEvent<HTMLInputElement>) =>
                  onUpdateNode(
                    node.id,
                    patchFetchConfig(node, { apiBaseUrl: e.target.value })
                  )
                }
                placeholder="https://api.example.com/v1"
                className="h-8 font-mono text-[11px]"
              />
            </label>
            <label className="block space-y-1">
              <span className="text-muted-foreground">{t("blueprint.config.selectEndpoint")}</span>
              <div className="flex gap-1.5">
                <div className="min-w-0 flex-1">
                  <FetchUrlAutocomplete
                    value={fetchConfig.url}
                    apiBaseUrl={fetchConfig.apiBaseUrl ?? ""}
                    endpoints={endpoints}
                    selectOnly
                    placeholder={t("blueprint.config.selectOrSearchEndpoint")}
                    onChange={(url) =>
                      onUpdateNode(node.id, patchFetchConfig(node, { url }))
                    }
                    onSelectEndpoint={(endpoint) =>
                      onUpdateNode(
                        node.id,
                        patchFetchConfig(node, {
                          url: endpoint.path,
                          method: endpoint.method,
                        })
                      )
                    }
                  />
                </div>
                <AsyncSendButton
                  loading={loadingFetchDebug}
                  disabled={loadingSwagger}
                  onSend={handleSendFetchDebug}
                  onAbort={handleAbortFetchDebug}
                  sendTitle={t("blueprint.config.sendDebugRequest")}
                  abortTitle={t("blueprint.config.abortRequest")}
                  sendAriaLabel={t("blueprint.config.sendDebugRequest")}
                  abortAriaLabel={t("blueprint.config.abortDebugAria")}
                />
              </div>
            </label>
          </div>
        ) : (
          <div className="flex gap-1.5">
            <Input
              value={fetchConfig.url}
              disabled={loadingFetchDebug}
              onChange={(e: ChangeEvent<HTMLInputElement>) =>
                onUpdateNode(node.id, patchFetchConfig(node, { url: e.target.value }))
              }
              placeholder="https://api.example.com/data"
              className="h-8 flex-1 font-mono text-[11px]"
            />
            <AsyncSendButton
              loading={loadingFetchDebug}
              disabled={loadingSwagger}
              onSend={handleSendFetchDebug}
              onAbort={handleAbortFetchDebug}
              sendTitle={t("blueprint.config.sendDebugRequest")}
              abortTitle={t("blueprint.config.abortRequest")}
              sendAriaLabel={t("blueprint.config.sendDebugRequest")}
              abortAriaLabel={t("blueprint.config.abortDebugAria")}
            />
          </div>
        )}
        {loadingFetchDebug ? (
          <p className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
            <LoaderIcon className="h-3.5 w-3.5 shrink-0" />
            {t("blueprint.config.sendingDebug")}
          </p>
        ) : null}
        {fetchValidationError ? (
          <p className="text-[11px] text-destructive">{fetchValidationError}</p>
        ) : null}
        <FetchDebugResponsePanel task={fetchDebugTask} />
      </label>

      <label className="block space-y-1">
        <span className="text-muted-foreground">{t("blueprint.config.requestMethod")}</span>
        <Select
          value={fetchConfig.method ?? "GET"}
          onValueChange={(value: string) =>
            onUpdateNode(
              node.id,
              patchFetchConfig(node, { method: value as FetchHttpMethod })
            )
          }
        >
          <SelectTrigger className="h-8">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {FETCH_HTTP_METHODS.map((method) => (
              <SelectItem key={method} value={method}>
                {method}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </label>

      <label className="block space-y-1">
        <span className="text-muted-foreground">{t("blueprint.config.requestHeadersJson")}</span>
        <textarea
          defaultValue={JSON.stringify(fetchConfig.headers ?? {}, null, 2)}
          key={`${node.id}-headers-${JSON.stringify(fetchConfig.headers)}`}
          onBlur={(e) => {
            try {
              const headers = JSON.parse(e.target.value || "{}") as Record<
                string,
                string
              >;
              onUpdateNode(node.id, patchFetchConfig(node, { headers }));
            } catch {
              /* 保留上次有效值 */
            }
          }}
          rows={4}
          className="w-full rounded-md border border-input bg-background px-2 py-1.5 font-mono text-[11px] leading-relaxed text-foreground shadow-sm outline-none focus-visible:ring-1 focus-visible:ring-primary"
          placeholder='{"Content-Type":"application/json"}'
        />
      </label>

      <label className="block space-y-1">
        <span className="text-muted-foreground">{t("blueprint.config.requestBody")}</span>
        <textarea
          value={fetchConfig.body ?? ""}
          onChange={(e) =>
            onUpdateNode(node.id, patchFetchConfig(node, { body: e.target.value }))
          }
          rows={4}
          className="w-full rounded-md border border-input bg-background px-2 py-1.5 font-mono text-[11px] leading-relaxed text-foreground shadow-sm outline-none focus-visible:ring-1 focus-visible:ring-primary"
          placeholder='{"key":"value"}'
        />
      </label>

      <div className="grid grid-cols-2 gap-2">
        <label className="block space-y-1">
          <span className="text-muted-foreground">Credentials</span>
          <Select
            value={fetchConfig.credentials ?? "same-origin"}
            onValueChange={(value: string) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, {
                  credentials: value as RequestCredentials,
                })
              )
            }
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {FETCH_CREDENTIALS.map((item) => (
                <SelectItem key={item} value={item}>
                  {item}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </label>
        <label className="block space-y-1">
          <span className="text-muted-foreground">Mode</span>
          <Select
            value={fetchConfig.mode ?? "cors"}
            onValueChange={(value: string) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { mode: value as RequestMode })
              )
            }
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {FETCH_MODES.map((item) => (
                <SelectItem key={item} value={item}>
                  {item}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </label>
        <label className="block space-y-1">
          <span className="text-muted-foreground">Cache</span>
          <Select
            value={fetchConfig.cache ?? "default"}
            onValueChange={(value: string) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { cache: value as RequestCache })
              )
            }
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {FETCH_CACHES.map((item) => (
                <SelectItem key={item} value={item}>
                  {item}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </label>
        <label className="block space-y-1">
          <span className="text-muted-foreground">Redirect</span>
          <Select
            value={fetchConfig.redirect ?? "follow"}
            onValueChange={(value: string) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, { redirect: value as RequestRedirect })
              )
            }
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {FETCH_REDIRECTS.map((item) => (
                <SelectItem key={item} value={item}>
                  {item}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </label>
      </div>

      <div className="grid grid-cols-2 gap-2">
        <label className="block space-y-1">
          <span className="text-muted-foreground">{t("blueprint.config.responseParse")}</span>
          <Select
            value={fetchConfig.responseType ?? "json"}
            onValueChange={(value: string) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, {
                  responseType: value as FetchResponseType,
                })
              )
            }
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {FETCH_RESPONSE_TYPES.map((item) => (
                <SelectItem key={item} value={item}>
                  {item}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </label>
        <label className="block space-y-1">
          <span className="text-muted-foreground">{t("blueprint.config.timeoutMs")}</span>
          <Input
            type="number"
            min={0}
            step={1000}
            value={fetchConfig.timeoutMs ?? 30000}
            onChange={(e: ChangeEvent<HTMLInputElement>) =>
              onUpdateNode(
                node.id,
                patchFetchConfig(node, {
                  timeoutMs: Number(e.target.value) || 0,
                })
              )
            }
            className="h-8"
          />
        </label>
      </div>
    </div>
  );
}
