// packages/react-blueprint/src/components/StorageNodeConfigPanel.tsx
import { useCallback, useMemo, useState, type ChangeEvent } from "react";
import {
  Checkbox,
  Input,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@arronqzy/ui";
import type {
  ExecutionTraceEntry,
  StorageKind,
  StorageReadConfig,
  StorageSetConfig,
} from "@arronqzy/blueprint-dsl";
import {
  latestTraceOutputsByNode,
  resolveFetchIncomingScope,
  resolveFetchScopeAutocompleteRoot,
  uniqueStorageKinds,
} from "@arronqzy/blueprint-dsl";
import { useI18n } from "@arronqzy/i18n/react";

import type { BlueprintGraphEdge, BlueprintGraphNode } from "../graph/document";
import { resolveNodeStorageConfig } from "../graph/document";
import { ConfigFieldLabel, ConfigSectionTitle } from "./ConfigHintIcon";
import { ScopeTemplateAutocompleteHost } from "./ScopeTemplateAutocompleteHost";
import { StorageKeyAutocomplete } from "./StorageKeyAutocomplete";

export type StorageNodeConfigPanelProps = {
  node: BlueprintGraphNode;
  graphNodes?: BlueprintGraphNode[];
  graphEdges?: BlueprintGraphEdge[];
  traceEntries?: ExecutionTraceEntry[];
  onUpdateNode: (
    nodeId: string,
    patch: Partial<Pick<BlueprintGraphNode, "storageConfig" | "configSource">>
  ) => void;
};

function patchStorageConfig(
  node: BlueprintGraphNode,
  patch: {
    read?: Partial<StorageReadConfig>;
    set?: Partial<StorageSetConfig>;
  }
) {
  const current = resolveNodeStorageConfig(node);
  return {
    storageConfig: {
      read: { ...current.read, ...patch.read },
      set: { ...current.set, ...patch.set },
    },
    configSource: "storage" as const,
  };
}

export function StorageNodeConfigPanel({
  node,
  graphNodes = [],
  graphEdges = [],
  traceEntries = [],
  onUpdateNode,
}: StorageNodeConfigPanelProps) {
  const { t } = useI18n();
  const [formEl, setFormEl] = useState<HTMLDivElement | null>(null);
  const storageConfig = resolveNodeStorageConfig(node);

  const incomingScope = useMemo(() => {
    const outputs = latestTraceOutputsByNode(traceEntries);
    return resolveFetchIncomingScope({
      fetchNodeId: node.id,
      nodes: graphNodes,
      edges: graphEdges,
      getOutput: (sourceId, port) => outputs[sourceId]?.[port],
    });
  }, [graphEdges, graphNodes, node.id, traceEntries]);
  const autocompleteScope = resolveFetchScopeAutocompleteRoot(incomingScope);

  const handleReadStorageChange = useCallback(
    (value: string) => {
      onUpdateNode(
        node.id,
        patchStorageConfig(node, {
          read: { storage: value === "session" ? "session" : "local" },
        })
      );
    },
    [node, onUpdateNode]
  );

  const handleReadKeyChange = useCallback(
    (key: string) => {
      onUpdateNode(
        node.id,
        patchStorageConfig(node, { read: { key } })
      );
    },
    [node, onUpdateNode]
  );

  const handleSetStorageToggle = useCallback(
    (kind: StorageKind, checked: boolean) => {
      const next = new Set(storageConfig.set.storages);
      if (checked) next.add(kind);
      else next.delete(kind);
      onUpdateNode(
        node.id,
        patchStorageConfig(node, {
          set: { storages: uniqueStorageKinds([...next]) },
        })
      );
    },
    [node, onUpdateNode, storageConfig.set.storages]
  );

  const handleSetKeyChange = useCallback(
    (key: string) => {
      onUpdateNode(
        node.id,
        patchStorageConfig(node, { set: { key } })
      );
    },
    [node, onUpdateNode]
  );

  const handleSetValueChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      onUpdateNode(
        node.id,
        patchStorageConfig(node, { set: { value: e.target.value } })
      );
    },
    [node, onUpdateNode]
  );

  const setKeySuggestionStorages = useMemo(
    () =>
      storageConfig.set.storages.length > 0
        ? storageConfig.set.storages
        : (["session", "local"] as const),
    [storageConfig.set.storages]
  );

  return (
    <div
      ref={setFormEl}
      className="space-y-2 rounded-md border border-border/70 bg-muted/20 p-2.5"
    >
      <ScopeTemplateAutocompleteHost
        scope={autocompleteScope}
        container={formEl}
      />
      <ConfigSectionTitle
        title={t("blueprint.config.storageTitle")}
        hint={t("blueprint.config.storageHint")}
      />

      <div className="space-y-2 rounded-md border border-border/60 bg-background/70 p-2">
        <ConfigSectionTitle
          title={t("blueprint.config.storageReadTitle")}
          hint={t("blueprint.config.storageReadHint")}
        />
        <label className="block space-y-1">
          <ConfigFieldLabel label={t("blueprint.config.storageTarget")} />
          <Select
            value={storageConfig.read.storage}
            onValueChange={handleReadStorageChange}
          >
            <SelectTrigger className="h-8">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="session">
                {t("blueprint.config.storageSession")}
              </SelectItem>
              <SelectItem value="local">
                {t("blueprint.config.storageLocal")}
              </SelectItem>
            </SelectContent>
          </Select>
        </label>
        <label className="block space-y-1">
          <ConfigFieldLabel label={t("blueprint.config.storageKey")} />
          <StorageKeyAutocomplete
            value={storageConfig.read.key}
            storages={storageConfig.read.storage}
            placeholder="key"
            onChange={handleReadKeyChange}
          />
        </label>
      </div>

      <div className="space-y-2 rounded-md border border-border/60 bg-background/70 p-2">
        <ConfigSectionTitle
          title={t("blueprint.config.storageSetTitle")}
          hint={t("blueprint.config.storageSetHint")}
        />
        <div className="space-y-1.5">
          <ConfigFieldLabel label={t("blueprint.config.storageTarget")} />
          {(["session", "local"] as const).map((kind) => {
            const checked = storageConfig.set.storages.includes(kind);
            return (
              <label key={kind} className="flex items-center gap-2">
                <Checkbox
                  checked={checked}
                  className="h-3.5 w-3.5 border-2 border-foreground/80 bg-background ring-1 ring-foreground/40 data-[state=checked]:border-primary data-[state=checked]:ring-primary/40"
                  onCheckedChange={(nextChecked: boolean | "indeterminate") => {
                    handleSetStorageToggle(kind, nextChecked === true);
                  }}
                />
                <span>
                  {kind === "session"
                    ? t("blueprint.config.storageSession")
                    : t("blueprint.config.storageLocal")}
                </span>
              </label>
            );
          })}
        </div>
        <label className="block space-y-1">
          <ConfigFieldLabel label={t("blueprint.config.storageKey")} />
          <StorageKeyAutocomplete
            value={storageConfig.set.key}
            storages={setKeySuggestionStorages}
            placeholder="key"
            onChange={handleSetKeyChange}
          />
        </label>
        <label className="block space-y-1">
          <ConfigFieldLabel
            label={t("blueprint.config.storageValue")}
            hint={t("blueprint.config.storageValueHint")}
          />
          <Input
            value={storageConfig.set.value}
            onChange={handleSetValueChange}
            spellCheck={false}
            className="h-8 font-mono text-[11px]"
            placeholder="{scope.value}"
          />
        </label>
      </div>
    </div>
  );
}

// packages/vue-blueprint/src/components/StorageNodeConfigPanel.vue
<script setup lang="ts">
import { useI18n } from "@arronqzy/i18n/vue";
import { computed, ref } from "vue";
import { Checkbox, Input, Select } from "ant-design-vue";
import type {
  ExecutionTraceEntry,
  StorageKind,
  StorageReadConfig,
  StorageSetConfig,
} from "@arronqzy/blueprint-dsl";
import {
  latestTraceOutputsByNode,
  resolveFetchIncomingScope,
  resolveFetchScopeAutocompleteRoot,
  uniqueStorageKinds,
} from "@arronqzy/blueprint-dsl";

import type { BlueprintGraphEdge, BlueprintGraphNode } from "../graph/document";
import { resolveNodeStorageConfig } from "../graph/document";
import ConfigHintIcon from "./ConfigHintIcon.vue";
import ScopeTemplateAutocompleteHost from "./ScopeTemplateAutocompleteHost.vue";
import StorageKeyAutocomplete from "./StorageKeyAutocomplete.vue";

const { t } = useI18n();

export type StorageNodeConfigPanelProps = {
  node: BlueprintGraphNode;
  graphNodes?: BlueprintGraphNode[];
  graphEdges?: BlueprintGraphEdge[];
  traceEntries?: ExecutionTraceEntry[];
  onUpdateNode: (
    nodeId: string,
    patch: Partial<Pick<BlueprintGraphNode, "storageConfig" | "configSource">>
  ) => void;
};

const props = withDefaults(defineProps<StorageNodeConfigPanelProps>(), {
  graphNodes: () => [],
  graphEdges: () => [],
  traceEntries: () => [],
});

const formRef = ref<HTMLDivElement | null>(null);
const storageConfig = computed(() => resolveNodeStorageConfig(props.node));
const incomingScope = computed(() => {
  const outputs = latestTraceOutputsByNode(props.traceEntries);
  return resolveFetchIncomingScope({
    fetchNodeId: props.node.id,
    nodes: props.graphNodes,
    edges: props.graphEdges,
    getOutput: (sourceId, port) => outputs[sourceId]?.[port],
  });
});
const autocompleteScope = computed(() =>
  resolveFetchScopeAutocompleteRoot(incomingScope.value)
);

function patchStorageConfig(
  node: BlueprintGraphNode,
  patch: {
    read?: Partial<StorageReadConfig>;
    set?: Partial<StorageSetConfig>;
  }
) {
  const current = resolveNodeStorageConfig(node);
  return {
    storageConfig: {
      read: { ...current.read, ...patch.read },
      set: { ...current.set, ...patch.set },
    },
    configSource: "storage" as const,
  };
}

function handleReadStorageChange(value: string) {
  props.onUpdateNode(
    props.node.id,
    patchStorageConfig(props.node, {
      read: { storage: value === "session" ? "session" : "local" },
    })
  );
}

function handleReadKeyChange(value: string) {
  props.onUpdateNode(
    props.node.id,
    patchStorageConfig(props.node, { read: { key: String(value ?? "") } })
  );
}

function handleSetStorageToggle(kind: StorageKind, checked: boolean) {
  const next = new Set(storageConfig.value.set.storages);
  if (checked) next.add(kind);
  else next.delete(kind);
  props.onUpdateNode(
    props.node.id,
    patchStorageConfig(props.node, {
      set: { storages: uniqueStorageKinds([...next]) },
    })
  );
}

function handleSetKeyChange(value: string) {
  props.onUpdateNode(
    props.node.id,
    patchStorageConfig(props.node, { set: { key: String(value ?? "") } })
  );
}

function handleSetValueChange(value: string) {
  props.onUpdateNode(
    props.node.id,
    patchStorageConfig(props.node, { set: { value: String(value ?? "") } })
  );
}

const setKeySuggestionStorages = computed(() =>
  storageConfig.value.set.storages.length > 0
    ? storageConfig.value.set.storages
    : (["session", "local"] as const)
);
</script>

<template>
  <div
    ref="formRef"
    class="space-y-2 rounded-md border border-border/70 bg-muted/20 p-2.5"
  >
    <ScopeTemplateAutocompleteHost :scope="autocompleteScope" :container-ref="formRef" />
    <div class="flex items-center gap-1.5">
      <div class="font-medium text-foreground">{{ t("blueprint.config.storageTitle") }}</div>
      <ConfigHintIcon :label="t('blueprint.config.storageTitle')">
        {{ t("blueprint.config.storageHint") }}
      </ConfigHintIcon>
    </div>

    <div class="space-y-2 rounded-md border border-border/60 bg-background/70 p-2">
      <div class="flex items-center gap-1.5">
        <div class="font-medium text-foreground">{{ t("blueprint.config.storageReadTitle") }}</div>
        <ConfigHintIcon :label="t('blueprint.config.storageReadTitle')">
          {{ t("blueprint.config.storageReadHint") }}
        </ConfigHintIcon>
      </div>
      <label class="block space-y-1">
        <span class="text-muted-foreground">{{ t("blueprint.config.storageTarget") }}</span>
        <Select
          size="small"
          class="w-full"
          :value="storageConfig.read.storage"
          @change="(v) => handleReadStorageChange(String(v))"
        >
          <Select.Option value="session">{{ t("blueprint.config.storageSession") }}</Select.Option>
          <Select.Option value="local">{{ t("blueprint.config.storageLocal") }}</Select.Option>
        </Select>
      </label>
      <label class="block space-y-1">
        <span class="text-muted-foreground">{{ t("blueprint.config.storageKey") }}</span>
        <StorageKeyAutocomplete
          :value="storageConfig.read.key"
          :storages="storageConfig.read.storage"
          placeholder="key"
          @change="handleReadKeyChange"
        />
      </label>
    </div>

    <div class="space-y-2 rounded-md border border-border/60 bg-background/70 p-2">
      <div class="flex items-center gap-1.5">
        <div class="font-medium text-foreground">{{ t("blueprint.config.storageSetTitle") }}</div>
        <ConfigHintIcon :label="t('blueprint.config.storageSetTitle')">
          {{ t("blueprint.config.storageSetHint") }}
        </ConfigHintIcon>
      </div>
      <div class="space-y-1.5">
        <span class="text-muted-foreground">{{ t("blueprint.config.storageTarget") }}</span>
        <label class="flex items-center gap-2">
          <Checkbox
            :checked="storageConfig.set.storages.includes('session')"
            class="mt-0.5"
            @update:checked="(v) => handleSetStorageToggle('session', Boolean(v))"
          />
          <span>{{ t("blueprint.config.storageSession") }}</span>
        </label>
        <label class="flex items-center gap-2">
          <Checkbox
            :checked="storageConfig.set.storages.includes('local')"
            class="mt-0.5"
            @update:checked="(v) => handleSetStorageToggle('local', Boolean(v))"
          />
          <span>{{ t("blueprint.config.storageLocal") }}</span>
        </label>
      </div>
      <label class="block space-y-1">
        <span class="text-muted-foreground">{{ t("blueprint.config.storageKey") }}</span>
        <StorageKeyAutocomplete
          :value="storageConfig.set.key"
          :storages="setKeySuggestionStorages"
          placeholder="key"
          @change="handleSetKeyChange"
        />
      </label>
      <label class="block space-y-1">
        <span class="inline-flex items-center gap-1 text-muted-foreground">
          {{ t("blueprint.config.storageValue") }}
          <ConfigHintIcon :label="t('blueprint.config.storageValue')">
            {{ t("blueprint.config.storageValueHint") }}
          </ConfigHintIcon>
        </span>
        <Input
          size="small"
          :value="storageConfig.set.value"
          spellcheck="false"
          class="font-mono text-[11px]"
          placeholder="{scope.value}"
          @update:value="(v) => handleSetValueChange(String(v ?? ''))"
        />
      </label>
    </div>
  </div>
</template>
