// packages/vue-view/src/panel/components/WorkspaceConfigSidebar.vue
<script setup lang="ts">
import { computed } from "vue";
import { Empty } from "ant-design-vue";
import {
  BlueprintExecutionLogPanel,
  BlueprintNodeConfigSidebar,
  type BlueprintGraphNode,
  type ExecutionLogSettings,
  type ExecutionTraceEntry,
} from "@arronqzy/vue-blueprint";
import type { PanelElement, PanelLayer, ReferenceCopyMode } from "../types";
import PanelConfigSidebar from "./PanelConfigSidebar.vue";

export type WorkspaceConfigFocus = "view" | "blueprint" | "blueprint-log";

export type PanelConfigSidebarProps = {
  selectedElement: PanelElement | null;
  selectedElements?: PanelElement[];
  layers: PanelLayer[];
  updateElement: (
    id: string,
    patch: Partial<PanelElement>,
    options?: { batchId?: string; meta?: Record<string, unknown> }
  ) => void;
  setReferenceCopyMode?: (id: string, mode: ReferenceCopyMode) => void;
  nodeZOrderLabel?: string;
  onExcludeSelectedNode?: (nodeId: string) => void;
  onAdjustNodeZOrder?: (
    nodeId: string,
    action: "bringForward" | "sendBackward" | "bringToFront" | "sendToBack"
  ) => void;
  viewElementScope?: unknown;
};

export type BlueprintExecutionLogViewProps = {
  entries: ExecutionTraceEntry[];
  settings: ExecutionLogSettings;
  onUpdateSettings: (patch: Partial<ExecutionLogSettings>) => void;
  onSave: () => void;
  onExport: () => void;
  onClear: () => void;
  onClearAllSaved?: () => void | Promise<void>;
  onApplyRetention: () => void;
  hasSavedRuns?: boolean;
  lifecyclePhase?: string;
};

export type WorkspaceConfigSidebarProps = Omit<
  PanelConfigSidebarProps,
  "selectedElement" | "selectedElements"
> & {
  configFocus: WorkspaceConfigFocus;
  executionLog?: BlueprintExecutionLogViewProps;
  selectedBlueprintNode: BlueprintGraphNode | null;
  allowFalseSignalPropagation?: boolean;
  onUpdateAllowFalseSignalPropagation?: (value: boolean) => void;
  onUpdateBlueprintNode: (
    nodeId: string,
    patch: Partial<
      Pick<
        BlueprintGraphNode,
        | "label"
        | "role"
        | "nodeType"
        | "configSource"
        | "viewElementId"
        | "viewElementIds"
        | "nestedBlueprintId"
        | "libraryBlueprintId"
        | "lifecyclePhase"
        | "fetchConfig"
        | "jsonConfig"
        | "logicConfig"
        | "clockConfig"
      >
    >
  ) => void;
  blueprintLibraryOptions?: { id: string; label: string }[];
  selectedElement: PanelElement | null;
  selectedElements?: PanelElement[];
  allViewElements: PanelElement[];
};

const props = withDefaults(
  defineProps<WorkspaceConfigSidebarProps>(),
  {
    allowFalseSignalPropagation: false,
    blueprintLibraryOptions: () => [],
    selectedElements: () => [],
  }
);

const viewElementOptions = computed(() =>
  props.allViewElements.map((el) => ({
    id: el.id,
    label: el.name?.trim() || el.chart?.title || el.materialType || el.id,
  }))
);
</script>

<template>
  <div class="flex h-full flex-col overflow-hidden bg-white">
    <PanelConfigSidebar
      v-if="configFocus === 'view'"
      :selected-element="selectedElement"
      :selected-elements="selectedElements"
      :layers="layers"
      :update-element="updateElement"
      :view-element-scope="viewElementScope"
      :set-reference-copy-mode="setReferenceCopyMode"
      :node-z-order-label="nodeZOrderLabel"
      :on-exclude-selected-node="onExcludeSelectedNode"
      :on-adjust-node-z-order="onAdjustNodeZOrder"
    />

    <BlueprintExecutionLogPanel
      v-else-if="configFocus === 'blueprint-log' && executionLog"
      :entries="executionLog.entries"
      :settings="executionLog.settings"
      :on-update-settings="executionLog.onUpdateSettings"
      :on-save="() => { if (executionLog) void executionLog.onSave(); }"
      :on-export="executionLog.onExport"
      :on-clear="executionLog.onClear"
      :on-clear-all-saved="executionLog.onClearAllSaved"
      :has-saved-runs="executionLog.hasSavedRuns"
      :on-apply-retention="() => { if (executionLog) void executionLog.onApplyRetention(); }"
      :lifecycle-phase="executionLog.lifecyclePhase"
    />

    <div
      v-else-if="!selectedBlueprintNode"
      class="flex h-full flex-col overflow-hidden bg-background text-foreground"
    >
      <Empty class="py-10" description="在蓝图面板中选中一个节点后，这里会显示对应的配置。" />
    </div>

    <BlueprintNodeConfigSidebar
      v-else
      :node="selectedBlueprintNode"
      :allow-false-signal-propagation="allowFalseSignalPropagation"
      :on-update-allow-false-signal-propagation="onUpdateAllowFalseSignalPropagation"
      :view-element-options="viewElementOptions"
      :blueprint-library-options="blueprintLibraryOptions"
      :on-update-node="onUpdateBlueprintNode"
    />
  </div>
</template>

// packages/react-view/src/panel/components/WorkspaceConfigSidebar.tsx
import { useMemo } from "react";

import {
  BlueprintExecutionLogPanel,
  BlueprintNodeConfigSidebar,
  type BlueprintGraphNode,
  type ExecutionLogSettings,
  type ExecutionTraceEntry,
} from "@arronqzy/react-blueprint";
import {
  Empty,
  EmptyDescription,
  EmptyIcon,
  EmptyTitle,
} from "@arronqzy/ui";

import type { PanelConfigSidebarProps } from "./PanelConfigSidebar";
import { PanelConfigSidebar } from "./PanelConfigSidebar";
import type { PanelElement } from "../types";

export type WorkspaceConfigFocus = "view" | "blueprint" | "blueprint-log";

export type BlueprintExecutionLogViewProps = {
  entries: ExecutionTraceEntry[];
  settings: ExecutionLogSettings;
  onUpdateSettings: (patch: Partial<ExecutionLogSettings>) => void;
  onSave: () => void;
  onExport: () => void;
  onClear: () => void;
  onClearAllSaved?: () => void | Promise<void>;
  onApplyRetention: () => void;
  hasSavedRuns?: boolean;
  lifecyclePhase?: string;
};

export type WorkspaceConfigSidebarProps = Omit<
  PanelConfigSidebarProps,
  "selectedElement" | "selectedElements"
> & {
  configFocus: WorkspaceConfigFocus;
  executionLog?: BlueprintExecutionLogViewProps;
  selectedBlueprintNode: BlueprintGraphNode | null;
  allowFalseSignalPropagation?: boolean;
  onUpdateAllowFalseSignalPropagation?: (value: boolean) => void;
  onUpdateBlueprintNode: (
    nodeId: string,
    patch: Partial<
      Pick<
        BlueprintGraphNode,
        | "label"
        | "role"
        | "nodeType"
        | "configSource"
        | "viewElementId"
        | "viewElementIds"
        | "nestedBlueprintId"
        | "libraryBlueprintId"
        | "lifecyclePhase"
        | "fetchConfig"
        | "jsonConfig"
        | "logicConfig"
        | "clockConfig"
      >
    >
  ) => void;
  blueprintLibraryOptions?: { id: string; label: string }[];
  selectedElement: PanelElement | null;
  selectedElements?: PanelElement[];
  allViewElements: PanelElement[];
};

export function WorkspaceConfigSidebar({
  configFocus,
  executionLog,
  selectedBlueprintNode,
  allowFalseSignalPropagation = false,
  onUpdateAllowFalseSignalPropagation,
  onUpdateBlueprintNode,
  blueprintLibraryOptions = [],
  selectedElement,
  selectedElements,
  allViewElements,
  ...viewPanelProps
}: WorkspaceConfigSidebarProps) {
  const viewElementOptions = useMemo(
    () =>
      allViewElements.map((el) => ({
        id: el.id,
        label: el.name?.trim() || el.chart?.title || el.materialType || el.id,
      })),
    [allViewElements]
  );

  if (configFocus === "view") {
    return (
      <PanelConfigSidebar
        {...viewPanelProps}
        selectedElement={selectedElement}
        selectedElements={selectedElements}
      />
    );
  }

  if (configFocus === "blueprint-log" && executionLog) {
    return (
      <BlueprintExecutionLogPanel
        entries={executionLog.entries}
        settings={executionLog.settings}
        onUpdateSettings={executionLog.onUpdateSettings}
        onSave={() => void executionLog.onSave()}
        onExport={executionLog.onExport}
        onClear={executionLog.onClear}
        onClearAllSaved={executionLog.onClearAllSaved}
        hasSavedRuns={executionLog.hasSavedRuns}
        onApplyRetention={() => void executionLog.onApplyRetention()}
        lifecyclePhase={executionLog.lifecyclePhase}
      />
    );
  }

  if (!selectedBlueprintNode) {
    return (
      <div className="flex h-full flex-col overflow-hidden bg-background text-foreground">
        <Empty className="py-10">
          <EmptyIcon>
            <svg
              viewBox="0 0 24 24"
              className="h-4 w-4"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
              aria-hidden="true"
            >
              <circle cx="6" cy="6" r="2" />
              <circle cx="18" cy="18" r="2" />
              <path d="M8 7l8 4M8 17l8-4" />
            </svg>
          </EmptyIcon>
          <EmptyTitle>未选中蓝图节点</EmptyTitle>
          <EmptyDescription>
            在蓝图面板中选中一个节点后，这里会显示对应的配置。
          </EmptyDescription>
        </Empty>
      </div>
    );
  }

  return (
    <BlueprintNodeConfigSidebar
      node={selectedBlueprintNode}
      allowFalseSignalPropagation={allowFalseSignalPropagation}
      onUpdateAllowFalseSignalPropagation={onUpdateAllowFalseSignalPropagation}
      viewElementOptions={viewElementOptions}
      blueprintLibraryOptions={blueprintLibraryOptions}
      onUpdateNode={onUpdateBlueprintNode}
    />
  );
}
